version: "3.8"
services:
  keycloak:
    image: alert-job/alert-job-keycloak:0.1
    #restart: always
    command:
      - "start-dev"
      - "--hostname-url=http://alertjob.by/keycloak"
      - "--hostname-admin-url=http://alertjob.by/keycloak"
      #- health-enabled=true
      #- metrics-enabled=true
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: alertjob.by
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /keycloak
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
#      - "443:443"
      - "80:80"
    volumes:
#      - html:/usr/share/nginx/html
      - ./config/vhost-nginx-dev:/etc/nginx/vhost.d
#      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx-conf-d:/etc/nginx/conf.d
    environment:
      TZ: Europe/Moscow
  config:
    image: rg.gdev.by/alert-job/alert-job-config:1.0
    ports:
      - "8011:8011"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
       - TZ=Europe/Moscow
  eureka:
    image: rg.gdev.by/alert-job/alert-job-eureka:1.0
    ports:
      - "8012:8012"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
       - TZ=Europe/Moscow
    depends_on:
      config:
        condition: service_healthy
  #set directory rules chmod 777 public
  gateway:
    image: rg.gdev.by/alert-job/alert-job-gateway:1.0
    ports:
      - "8015:8015"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: Europe/Moscow
      VIRTUAL_HOST: alertjob.by
      VIRTUAL_PORT: 8015
      VIRTUAL_PATH: /
    #extra_hosts:
     #   - "aj.by:nginx-alert-job" #host and ip
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  notification:
    image: rg.gdev.by/alert-job/notification-alert-job:1.0
    ports:
      - "8019:8019"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
       - TZ=Europe/Moscow
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  parser:
    image: rg.gdev.by/alert-job/parser-alert-job:1.0
    ports:
      - "8017:8017"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
       - TZ=Europe/Moscow
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  core:
    image: rg.gdev.by/alert-job/core-alert-job:1.0
    ports:
      - "8018:8018"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
       - TZ=Europe/Moscow
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    container_name: grafana 
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    volumes:
    - grafana-volume:/var/lib/grafana
  front:
    image: rg.gdev.by/alert-job/front:1.0
    environment:
      VIRTUAL_HOST: alertjob.by
      VIRTUAL_PATH: /front
      TZ: Europe/Moscow
    mem_limit: 256m
  adminer:
    image: adminer
    restart: always
    environment:
      VIRTUAL_HOST: alertjob.by
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /db
volumes:
  grafana-volume: {}  
networks:
  alert-job:
    driver: bridge      
      