version: "3.9"
services:
  db:
    image: mariadb:10.9.4-jammy
    ports:
      - 3307:3306
    volumes:
      - ~/prod/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$database_user_password
      - MYSQL_PASSWORD=$database_user_password
      - MYSQL_USER=$database_user_login
      - MYSQL_DATABASE=keycloak
  dbcore:
    image: mariadb:10.9.4-jammy
    ports:
      - 3310:3310
    volumes:
      - ~/prod/apps/mariadbcore:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$database_user_password
      - MYSQL_PASSWORD=$database_user_password
      - MYSQL_USER=$database_user_login
      - MYSQL_DATABASE=dbcore
  dbparser:
    image: mariadb:10.9.4-jammy
    ports:
      - 3311:3311
    volumes:
      - ~/prod/apps/mariadbparser:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$database_user_password
      - MYSQL_PASSWORD=$database_user_password
      - MYSQL_USER=$database_user_login
      - MYSQL_DATABASE=dbparser
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    command:
      - "start"
      - "--hostname-url=$keycloak_url"
      - "--hostname-admin-url=$keycloak_url"
      - "--db mariadb"
      - "--db-url-host db"
      - "--db-username $database_user_login"
      - "--db-password $database_user_password"
      #- health-enabled=true
      #- metrics-enabled=true
    ports:
      - "8080:8080"
    environment:
      - "KC_HTTP_ENABLED=true"
      - "KC_PROXY=edge"
      - "KEYCLOAK_ADMIN=$keycloak_admin"
      - "KEYCLOAK_ADMIN_PASSWORD=$keycloak_admin_password"
      - "KEYCLOAK_USER=$keycloak_admin"
      - "KEYCLOAK_PASSWORD=$keycloak_admin_password"
    depends_on:
      - db
  config:
    image: alert-job/alert-job-config:0.0.1-SNAPSHOT
    ports:
      - "8011:8011"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev,native"
      - "spring.cloud.config.server.native.search-locations=file://$configuration_override_parameters_directory_docker"
    volumes:
      - "$local_config_directory:$configuration_override_parameters_directory_docker"
  eureka:
    image: alert-job/alert-job-eureka:0.0.1-SNAPSHOT
    ports:
      - "8012:8012"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
  gateway:
    image: alert-job/alert-job-gateway:0.0.1-SNAPSHOT
    ports:
      - "8015:8015"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  notification:
    image: alert-job/notification-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8016:8016"
    environment:
       - SPRING_PROFILES_ACTIVE=prod
       - telegram.chat.token=$telegram_chat_token
       - mail.login=$mail_login
       - mail.password=$mail_pasword
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  parser:
    image: alert-job/parser-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8017:8017"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
       - spring.datasource.username=$database_user_login
       - spring.datasource.password=$database_user_password
       - spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
       - "spring.datasource.url=jdbc:maraidb://dbparser:3311/dbcore?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true"
       - spring.datasource.driverClassName=org.mariadb.jdbc.Driver
       - parser.categories.file.path=$parser_categories_file_path
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      dbparser:
        condition: service_started
        
  core:
    image: alert-job/core-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8018:8018"
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
       - spring.datasource.username=$database_user_login
       - spring.datasource.password=$database_user_password
       - spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
       - "spring.datasource.url=jdbc:maraidb://dbcore:3310/dbcore?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true"
       - spring.datasource.driverClassName=org.mariadb.jdbc.Driver
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      dbcore:
        condition: service_started
        
      
