version: "3.9"
services:
  db:
    image: mariadb:10.9.4-jammy
    ports:
      - 3307:3306
    volumes:
      - ~/prod/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$database_user_password
      - MYSQL_PASSWORD=$database_user_password
      - MYSQL_USER=$database_user_login
      - MYSQL_DATABASE=keycloak
  keycloak:
    image: alert-job/alert-job-keycloak:0.1
    #restart: always
    command:
      - "start"
      - "--hostname-url=http://aj.by/keycloak"
      - "--hostname-admin-url=http://aj.by/keycloak"
      - "--db mariadb"
      - "--db-url-host db"
      - "--db-username $database_user_login"
      - "--db-password $database_user_password"
      
      #- health-enabled=true
      #- metrics-enabled=true
    ports:
      - "8080:8080"
    environment:
      - "KC_HTTP_ENABLED=true"
      - "KC_PROXY=edge"
  nginx:
    image: nginx:1.23.3
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./front:/etc/alert-job-front"
    ports:
      - "80:80"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
  depends_on:
      keycloak:
        condition: service_healthy
  config:
    image: alert-job/alert-job-config:0.0.1-SNAPSHOT
    ports:
      - "8011:8011"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
  eureka:
    image: alert-job/alert-job-eureka:0.0.1-SNAPSHOT
    ports:
      - "8012:8012"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
  test-service:
    image: alert-job/alert-job-test-service:0.0.1-SNAPSHOT
    ports:
      - "8013:8013"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  test1-service:
    image: alert-job/alert-job-test1-service:0.0.1-SNAPSHOT
    ports:
      - "8014:8014"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  gateway:
    image: alert-job/alert-job-gateway:0.0.1-SNAPSHOT
    ports:
      - "8015:8015"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    links:
      - "nginx:aj.by"
    #extra_hosts:
     #   - "aj.by:nginx-alert-job" #host and ip
    healthcheck:
      test: curl --fail http://keycloak:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      #keycloak:
       # condition: service_healthy
  email:
    image: alert-job/email-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8016:8016"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  parser:
    image: alert-job/parser-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8017:8017"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  core:
    image: alert-job/core-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8018:8018"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
