version: "3.8"
services:
  keycloak:
    image: alert-job/alert-job-keycloak:0.1
    #restart: always
    command:
      - "start-dev"
      - "--hostname-url=http://auth.alertjob.by"
      - "--hostname-admin-url=http://auth.alertjob.by"
      
      #- health-enabled=true
      #- metrics-enabled=true
    ports:
      - "8080:8080"
  nginx:
    image: nginx:1.23.3
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./front:/etc/alert-job-front"
    ports:
      - "80:80"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      - gateway
      - keycloak
    networks:
      default:
        aliases:
          - alertjob.by
          - auth.alertjob.by
  config:
    image: alert-job/alert-job-config:0.0.1-SNAPSHOT
    ports:
      - "8011:8011"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
  eureka:
    image: alert-job/alert-job-eureka:0.0.1-SNAPSHOT
    ports:
      - "8012:8012"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
  test-service:
    image: alert-job/alert-job-test-service:0.0.1-SNAPSHOT
    ports:
      - "8013:8013"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  test1-service:
    image: alert-job/alert-job-test1-service:0.0.1-SNAPSHOT
    ports:
      - "8014:8014"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  gateway:
    image: alert-job/alert-job-gateway:0.0.1-SNAPSHOT
    ports:
      - "8015:8015"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    #extra_hosts:
     #   - "aj.by:nginx-alert-job" #host and ip
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  notification:
    image: alert-job/notification-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8016:8016"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  parser:
    image: alert-job/parser-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8017:8017"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
  core:
    image: alert-job/core-alert-job:0.0.1-SNAPSHOT
    ports:
      - "8018:8018"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
