version: "3.9"
services:
  nginx-proxy:
    restart: always
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - html:/usr/share/nginx/html
      - ./config/vhost-nginx:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx-conf-d:/etc/nginx/conf.d
    environment:
      TZ: Europe/Moscow
  nginx-proxy-acme:
    restart: always
    image: nginxproxy/acme-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - ./config/vhost-nginx:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: $acme_email
      NGINX_PROXY_CONTAINER: nginx-proxy
      TZ: Europe/Moscow
     # - HTTPS_METHOD=redirect
    depends_on:
      - "nginx-proxy"
  db:
    restart: always
    image: mariadb:11.1.2-jammy
    volumes:
      - database-volume:/var/lib/mysql
      - ./config/database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=$database_user_password
      - MYSQL_USER=alert_job_user
      - MYSQL_PASSWORD=$database_user_password
      - TZ=Europe/Moscow
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak
    command:
      - "start"
      - "--hostname-url=https://$domain/keycloak"
      - "--hostname-admin-url=https://$domain/keycloak"
      - "--db mariadb"
      - "--db-url-host db"
      - "--db-username alert_job_user"
      - "--db-password $database_user_password"
      #- health-enabled=true
      #- metrics-enabled=true
    environment:
      VIRTUAL_HOST: $domain
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /keycloak
      LETSENCRYPT_HOST: $domain
#      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KEYCLOAK_ADMIN: $keycloak_admin
      KEYCLOAK_ADMIN_PASSWORD: $keycloak_admin_password
      KEYCLOAK_USER: $keycloak_admin
      KEYCLOAK_PASSWORD: $keycloak_admin_password
      TZ: Europe/Moscow
    depends_on:
      - db
    mem_limit: 612m
  config:
    restart: always
    image: rg.gdev.by/alert-job/alert-job-config:$alert_job_version
    environment:
      - "SPRING_PROFILES_ACTIVE=dev,native"
      - "spring.cloud.config.server.native.search-locations=file:///alert-job-config-repo"
      - "spring.cloud.config.server.overrides.logging.level.by.gdev=$logger_level"
      - TZ=Europe/Moscow
    volumes:
      - "$local_config_directory:/alert-job-config-repo"
    mem_limit: 512m
  eureka:
    restart: always
    image: rg.gdev.by/alert-job/alert-job-eureka:$alert_job_version 
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
       - TZ=Europe/Moscow
    depends_on:
      config:
        condition: service_healthy
    mem_limit: 512m
  #set directory rules sudo chmod 777 files_prod/elasticsearc
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./config/loki:/etc/loki
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    deploy:
      resources:
        limits:
          cpus: '1.0'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./config/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # Логи контейнеров
      - /var/log:/var/log:ro  # Системные логи
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Сокет Docker
    command: -config.file=/etc/promtail/promtail-config.yaml
    deploy:
      resources:
        limits:
          cpus: '1.0'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  gateway:
    restart: always
    image: rg.gdev.by/alert-job/alert-job-gateway:$alert_job_version
    environment:
      VIRTUAL_HOST: $domain
      VIRTUAL_PATH: /
      LETSENCRYPT_HOST: $domain
      LETSENCRYPT_EMAIL: $acme_email
      VIRTUAL_PORT: 8015
      SPRING_PROFILES_ACTIVE: prod
      TZ: Europe/Moscow
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    mem_limit: 512m
  notification:
    restart: always
    image: rg.gdev.by/alert-job/notification-alert-job:$alert_job_version
    environment:
       - SPRING_PROFILES_ACTIVE=prod
       - TZ=Europe/Moscow
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    mem_limit: 512m
  parser:
    restart: always
    image: rg.gdev.by/alert-job/parser-alert-job:$alert_job_version
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
       - TZ=Europe/Moscow
    volumes:
       - "$parser_config_directory:/etc/parser/config"
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      db:
        condition: service_started
    mem_limit: 2g
  core:
    restart: always
    image: rg.gdev.by/alert-job/core-alert-job:$alert_job_version
    environment:
       - "SPRING_PROFILES_ACTIVE=prod"
       - TZ=Europe/Moscow
    depends_on:
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
      db:
        condition: service_started
    mem_limit: 2g  
  prometheus:
    restart: always
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - $prometheus_directory/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      TZ: Europe/Moscow
  grafana:
    restart: always
    container_name: grafana 
    image: "grafana/grafana:latest"
    volumes:
    - grafana-volume:/var/lib/grafana
    environment:
      VIRTUAL_HOST: $grafana_domain
      LETSENCRYPT_EMAIL: $acme_email
      LETSENCRYPT_HOST: $grafana_domain
      VIRTUAL_PORT: 3000
      GF_SERVER_ROOT_URL: "https://$grafana_domain"
      GF_SERVER_DOMAIN: $grafana_domain
      TZ: Europe/Moscow
  adminer:
    image: adminer
    restart: always
    environment:
      VIRTUAL_HOST: $domain
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /db
      LETSENCRYPT_HOST: $domain
volumes:
  database-volume: {}
  grafana-volume: {}
  certs: {}      
  vhost: {}
  html: {}
  nginx-conf-d: {}
  acme: {}
  loki-data: {}
networks:
  alert-job:
    driver: bridge      