/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Информация о пользователе, связанная с заказами
 */
export interface AiAppUserDTO {
    /**
     * UUID пользователя
     */
    'uuid'?: string;
    /**
     * Email пользователя
     */
    'email'?: string;
    /**
     * Telegram ID пользователя
     */
    'telegram'?: number;
    /**
     * Флаг отключения уведомлений
     */
    'switchOffAlerts'?: boolean;
    /**
     * Тип отправки по умолчанию: true = email, false = telegram
     */
    'defaultSendType'?: boolean;
}
/**
 * Информация о модуле, от имени которого отправлены заказы
 */
export interface AiOrderModulesDTO {
    /**
     * ID модуля
     */
    'id'?: number;
    /**
     * Название модуля
     */
    'name'?: string;
}
/**
 * Расширенный запрос для AI, содержащий пользователя, модуль и список заказов
 */
export interface AiOrderRequest {
    'user'?: AiAppUserDTO;
    'module'?: AiOrderModulesDTO;
    /**
     * ID учётных данных пользователя (credential), связанных с модулем
     */
    'credentialId'?: number;
    /**
     * ID шаблона, который должен использоваться для генерации ответа
     */
    'templateId'?: number;
    /**
     * ID промта, который должен использоваться для генерации ответа
     */
    'promtId'?: number;
    'orders'?: OrderDTO;
    'notificationType'?: AiOrderRequestNotificationTypeEnum;
}

export const AiOrderRequestNotificationTypeEnum = {
    None: 'NONE',
    Email: 'EMAIL',
    Telegram: 'TELEGRAM',
} as const;

export type AiOrderRequestNotificationTypeEnum = typeof AiOrderRequestNotificationTypeEnum[keyof typeof AiOrderRequestNotificationTypeEnum];

/**
 * Описание промта. Используется в списках и UI.
 */
export interface AiPromptDto {
    /**
     * ID промта в базе данных
     */
    'id': number;
    /**
     * Версия промта (инкрементируется при обновлении)
     */
    'version': number;
    /**
     * Имя промта
     */
    'name': string;
    /**
     * Текст промта
     */
    'text': string;
    /**
     * Дата создания промта
     */
    'createdAt': string;
    /**
     * Дата последнего обновления промта
     */
    'updatedAt': string;
}
/**
 * Информация о заказе, полученном с внешнего сайта
 */
export interface OrderDTO {
    /**
     * Заголовок заказа
     */
    'title'?: string;
    /**
     * Полное описание заказа
     */
    'message'?: string;
    /**
     * Ссылка на заказ
     */
    'link'?: string;
    /**
     * Дата и время публикации заказа
     */
    'dateTime'?: string;
    'price'?: PriceDTO;
    'sourceSite'?: SourceSiteDTO;
    /**
     * Название модуля, который обработал заказ
     */
    'moduleName'?: string;
    /**
     * Флаг: заказ открыт для всех пользователей
     */
    'openForAll'?: boolean;
    /**
     * Флаг валидности заказа (например, не удалён, не скрыт)
     */
    'validOrder'?: boolean;
}
/**
 * Информация о цене заказа
 */
export interface PriceDTO {
    /**
     * Цена в текстовом виде (как на сайте)
     */
    'price'?: string;
    /**
     * Цена в числовом виде (например рубли/доллары)
     */
    'value'?: number;
}
/**
 * Запрос на создание или обновление промта
 */
export interface PromptRequest {
    /**
     * Название промта
     */
    'name': string;
    /**
     * Текст промта
     */
    'text': string;
}
/**
 * Информация об источнике заказа: сайт, категория и подкатегория
 */
export interface SourceSiteDTO {
    /**
     * ID записи источника
     */
    'id'?: number;
    /**
     * ID сайта, откуда пришёл заказ
     */
    'source'?: number;
    /**
     * Название сайта-источника
     */
    'sourceName'?: string;
    /**
     * ID категории заказа
     */
    'category'?: number;
    /**
     * Название категории
     */
    'categoryName'?: string;
    /**
     * ID подкатегории заказа
     */
    'subCategory'?: number;
    /**
     * Название подкатегории
     */
    'subCategoryName'?: string;
}
/**
 * Запрос на создание или обновление шаблона
 */
export interface TemplateRequest {
    /**
     * Название шаблона
     */
    'name': string;
    /**
     * Содержимое шаблона (HTML)
     */
    'text': string;
}
/**
 * Ответ с информацией о шаблоне HTML для автоответов
 */
export interface TemplateResponse {
    /**
     * Название шаблона
     */
    'name': string;
    /**
     * Уникальный идентификатор шаблона
     */
    'id': number;
    /**
     * Cодержимое шаблона (HTML)
     */
    'text': string;
    /**
     * Дата создания шаблона
     */
    'createdAt': string;
}

/**
 * OrdersApi - axios parameter creator
 */
export const OrdersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Принимает расширенный объект AiOrderRequest, содержащий: • список заказов, • данные пользователя, • данные модуля.  Используется для более точной обработки заказов с учётом контекста. 
         * @summary Получить заказы с дополнительной информацией (пользователь, модуль, шаблон и т.д.)
         * @param {AiOrderRequest} aiOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiveAiOrderRequest: async (aiOrderRequest: AiOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'aiOrderRequest' is not null or undefined
            assertParamExists('receiveAiOrderRequest', 'aiOrderRequest', aiOrderRequest)
            const localVarPath = `/ai/api/orders/context`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(aiOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrdersApi - functional programming interface
 */
export const OrdersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrdersApiAxiosParamCreator(configuration)
    return {
        /**
         * Принимает расширенный объект AiOrderRequest, содержащий: • список заказов, • данные пользователя, • данные модуля.  Используется для более точной обработки заказов с учётом контекста. 
         * @summary Получить заказы с дополнительной информацией (пользователь, модуль, шаблон и т.д.)
         * @param {AiOrderRequest} aiOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async receiveAiOrderRequest(aiOrderRequest: AiOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.receiveAiOrderRequest(aiOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrdersApi.receiveAiOrderRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrdersApi - factory interface
 */
export const OrdersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrdersApiFp(configuration)
    return {
        /**
         * Принимает расширенный объект AiOrderRequest, содержащий: • список заказов, • данные пользователя, • данные модуля.  Используется для более точной обработки заказов с учётом контекста. 
         * @summary Получить заказы с дополнительной информацией (пользователь, модуль, шаблон и т.д.)
         * @param {AiOrderRequest} aiOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiveAiOrderRequest(aiOrderRequest: AiOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.receiveAiOrderRequest(aiOrderRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrdersApi - object-oriented interface
 */
export class OrdersApi extends BaseAPI {
    /**
     * Принимает расширенный объект AiOrderRequest, содержащий: • список заказов, • данные пользователя, • данные модуля.  Используется для более точной обработки заказов с учётом контекста. 
     * @summary Получить заказы с дополнительной информацией (пользователь, модуль, шаблон и т.д.)
     * @param {AiOrderRequest} aiOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public receiveAiOrderRequest(aiOrderRequest: AiOrderRequest, options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).receiveAiOrderRequest(aiOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PromptsApi - axios parameter creator
 */
export const PromptsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает true, если промт существует и доступен пользователю (глобальный или принадлежит пользователю).
         * @summary Проверить существование промта
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkPromptExists: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('checkPromptExists', 'id', id)
            const localVarPath = `/api/prompts/{id}/exists`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Создаёт новый промт или обновляет существующий по имени. Если промт с таким именем уже существует у пользователя, он будет обновлён (версия увеличится). Иначе создаётся новый промт.
         * @summary Создать или обновить промт
         * @param {PromptRequest} promptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate1: async (promptRequest: PromptRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'promptRequest' is not null or undefined
            assertParamExists('createOrUpdate1', 'promptRequest', promptRequest)
            const localVarPath = `/api/prompts/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(promptRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет промт по ID. Можно удалять только свои промты. Системный DEFAULT_PROMPT удалить нельзя.
         * @summary Удалить промт
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePrompt: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePrompt', 'id', id)
            const localVarPath = `/api/prompts/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает глобальный DEFAULT_PROMPT (DTO). Используется, когда пользовательский промт не найден или ID невалидный.
         * @summary Получить промт по умолчанию
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDefaultPrompt: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/prompts/default`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает DTO промта по ID. Если промт не найден или недоступен пользователю, возвращается DEFAULT_PROMPT.
         * @summary Получить промт по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPromptById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPromptById', 'id', id)
            const localVarPath = `/api/prompts/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список всех промтов, принадлежащих пользователю, включая системный DEFAULT_PROMPT.
         * @summary Получить все промты пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPromptsByUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/prompts/user/my`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PromptsApi - functional programming interface
 */
export const PromptsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PromptsApiAxiosParamCreator(configuration)
    return {
        /**
         * Возвращает true, если промт существует и доступен пользователю (глобальный или принадлежит пользователю).
         * @summary Проверить существование промта
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkPromptExists(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkPromptExists(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.checkPromptExists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Создаёт новый промт или обновляет существующий по имени. Если промт с таким именем уже существует у пользователя, он будет обновлён (версия увеличится). Иначе создаётся новый промт.
         * @summary Создать или обновить промт
         * @param {PromptRequest} promptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrUpdate1(promptRequest: PromptRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrUpdate1(promptRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.createOrUpdate1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет промт по ID. Можно удалять только свои промты. Системный DEFAULT_PROMPT удалить нельзя.
         * @summary Удалить промт
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePrompt(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePrompt(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.deletePrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает глобальный DEFAULT_PROMPT (DTO). Используется, когда пользовательский промт не найден или ID невалидный.
         * @summary Получить промт по умолчанию
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDefaultPrompt(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AiPromptDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDefaultPrompt(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.getDefaultPrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает DTO промта по ID. Если промт не найден или недоступен пользователю, возвращается DEFAULT_PROMPT.
         * @summary Получить промт по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPromptById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AiPromptDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPromptById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.getPromptById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список всех промтов, принадлежащих пользователю, включая системный DEFAULT_PROMPT.
         * @summary Получить все промты пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPromptsByUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AiPromptDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPromptsByUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromptsApi.getPromptsByUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PromptsApi - factory interface
 */
export const PromptsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PromptsApiFp(configuration)
    return {
        /**
         * Возвращает true, если промт существует и доступен пользователю (глобальный или принадлежит пользователю).
         * @summary Проверить существование промта
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkPromptExists(id: number, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.checkPromptExists(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Создаёт новый промт или обновляет существующий по имени. Если промт с таким именем уже существует у пользователя, он будет обновлён (версия увеличится). Иначе создаётся новый промт.
         * @summary Создать или обновить промт
         * @param {PromptRequest} promptRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate1(promptRequest: PromptRequest, options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.createOrUpdate1(promptRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет промт по ID. Можно удалять только свои промты. Системный DEFAULT_PROMPT удалить нельзя.
         * @summary Удалить промт
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePrompt(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deletePrompt(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает глобальный DEFAULT_PROMPT (DTO). Используется, когда пользовательский промт не найден или ID невалидный.
         * @summary Получить промт по умолчанию
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDefaultPrompt(options?: RawAxiosRequestConfig): AxiosPromise<AiPromptDto> {
            return localVarFp.getDefaultPrompt(options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает DTO промта по ID. Если промт не найден или недоступен пользователю, возвращается DEFAULT_PROMPT.
         * @summary Получить промт по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPromptById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AiPromptDto> {
            return localVarFp.getPromptById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список всех промтов, принадлежащих пользователю, включая системный DEFAULT_PROMPT.
         * @summary Получить все промты пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPromptsByUser(options?: RawAxiosRequestConfig): AxiosPromise<Array<AiPromptDto>> {
            return localVarFp.getPromptsByUser(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PromptsApi - object-oriented interface
 */
export class PromptsApi extends BaseAPI {
    /**
     * Возвращает true, если промт существует и доступен пользователю (глобальный или принадлежит пользователю).
     * @summary Проверить существование промта
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public checkPromptExists(id: number, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).checkPromptExists(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Создаёт новый промт или обновляет существующий по имени. Если промт с таким именем уже существует у пользователя, он будет обновлён (версия увеличится). Иначе создаётся новый промт.
     * @summary Создать или обновить промт
     * @param {PromptRequest} promptRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOrUpdate1(promptRequest: PromptRequest, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).createOrUpdate1(promptRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет промт по ID. Можно удалять только свои промты. Системный DEFAULT_PROMPT удалить нельзя.
     * @summary Удалить промт
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePrompt(id: number, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).deletePrompt(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает глобальный DEFAULT_PROMPT (DTO). Используется, когда пользовательский промт не найден или ID невалидный.
     * @summary Получить промт по умолчанию
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDefaultPrompt(options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).getDefaultPrompt(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает DTO промта по ID. Если промт не найден или недоступен пользователю, возвращается DEFAULT_PROMPT.
     * @summary Получить промт по ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPromptById(id: number, options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).getPromptById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список всех промтов, принадлежащих пользователю, включая системный DEFAULT_PROMPT.
     * @summary Получить все промты пользователя
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPromptsByUser(options?: RawAxiosRequestConfig) {
        return PromptsApiFp(this.configuration).getPromptsByUser(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TemplatesApi - axios parameter creator
 */
export const TemplatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Создаёт новый HTML‑шаблон или обновляет существующий. Возвращает ID созданного/обновлённого шаблона.
         * @summary Создать или обновить шаблон
         * @param {TemplateRequest} templateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate: async (templateRequest: TemplateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'templateRequest' is not null or undefined
            assertParamExists('createOrUpdate', 'templateRequest', templateRequest)
            const localVarPath = `/api/templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(templateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет шаблон по ID. Можно удалять только свои шаблоны. Системный DEFAULT_TEMPLATE удалить нельзя.
         * @summary Удалить шаблон
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTemplate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteTemplate', 'id', id)
            const localVarPath = `/api/templates/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает true/false в зависимости от того, существует ли шаблон.
         * @summary Проверить существование шаблона
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exists: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('exists', 'id', id)
            const localVarPath = `/api/templates/{id}/exists`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает полную информацию о шаблоне.
         * @summary Получить шаблон по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplateById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTemplateById', 'id', id)
            const localVarPath = `/api/templates/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список всех шаблонов, созданных пользователем, включая системный DEFAULT_TEMPLATE.
         * @summary Получить шаблоны пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplatesByUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/templates/user/my`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TemplatesApi - functional programming interface
 */
export const TemplatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TemplatesApiAxiosParamCreator(configuration)
    return {
        /**
         * Создаёт новый HTML‑шаблон или обновляет существующий. Возвращает ID созданного/обновлённого шаблона.
         * @summary Создать или обновить шаблон
         * @param {TemplateRequest} templateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrUpdate(templateRequest: TemplateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrUpdate(templateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TemplatesApi.createOrUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет шаблон по ID. Можно удалять только свои шаблоны. Системный DEFAULT_TEMPLATE удалить нельзя.
         * @summary Удалить шаблон
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTemplate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTemplate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TemplatesApi.deleteTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает true/false в зависимости от того, существует ли шаблон.
         * @summary Проверить существование шаблона
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exists(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exists(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TemplatesApi.exists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает полную информацию о шаблоне.
         * @summary Получить шаблон по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplateById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TemplateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTemplateById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TemplatesApi.getTemplateById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список всех шаблонов, созданных пользователем, включая системный DEFAULT_TEMPLATE.
         * @summary Получить шаблоны пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplatesByUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TemplateResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTemplatesByUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TemplatesApi.getTemplatesByUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TemplatesApi - factory interface
 */
export const TemplatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TemplatesApiFp(configuration)
    return {
        /**
         * Создаёт новый HTML‑шаблон или обновляет существующий. Возвращает ID созданного/обновлённого шаблона.
         * @summary Создать или обновить шаблон
         * @param {TemplateRequest} templateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate(templateRequest: TemplateRequest, options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.createOrUpdate(templateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет шаблон по ID. Можно удалять только свои шаблоны. Системный DEFAULT_TEMPLATE удалить нельзя.
         * @summary Удалить шаблон
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTemplate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.deleteTemplate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает true/false в зависимости от того, существует ли шаблон.
         * @summary Проверить существование шаблона
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exists(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.exists(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает полную информацию о шаблоне.
         * @summary Получить шаблон по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplateById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<TemplateResponse> {
            return localVarFp.getTemplateById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список всех шаблонов, созданных пользователем, включая системный DEFAULT_TEMPLATE.
         * @summary Получить шаблоны пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplatesByUser(options?: RawAxiosRequestConfig): AxiosPromise<Array<TemplateResponse>> {
            return localVarFp.getTemplatesByUser(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TemplatesApi - object-oriented interface
 */
export class TemplatesApi extends BaseAPI {
    /**
     * Создаёт новый HTML‑шаблон или обновляет существующий. Возвращает ID созданного/обновлённого шаблона.
     * @summary Создать или обновить шаблон
     * @param {TemplateRequest} templateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOrUpdate(templateRequest: TemplateRequest, options?: RawAxiosRequestConfig) {
        return TemplatesApiFp(this.configuration).createOrUpdate(templateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет шаблон по ID. Можно удалять только свои шаблоны. Системный DEFAULT_TEMPLATE удалить нельзя.
     * @summary Удалить шаблон
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTemplate(id: number, options?: RawAxiosRequestConfig) {
        return TemplatesApiFp(this.configuration).deleteTemplate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает true/false в зависимости от того, существует ли шаблон.
     * @summary Проверить существование шаблона
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exists(id: number, options?: RawAxiosRequestConfig) {
        return TemplatesApiFp(this.configuration).exists(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает полную информацию о шаблоне.
     * @summary Получить шаблон по ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTemplateById(id: number, options?: RawAxiosRequestConfig) {
        return TemplatesApiFp(this.configuration).getTemplateById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список всех шаблонов, созданных пользователем, включая системный DEFAULT_TEMPLATE.
     * @summary Получить шаблоны пользователя
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTemplatesByUser(options?: RawAxiosRequestConfig) {
        return TemplatesApiFp(this.configuration).getTemplatesByUser(options).then((request) => request(this.axios, this.basePath));
    }
}



