/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Информация о пользователе, связанная с заказами
 */
export interface AiAppUserDTO {
    /**
     * UUID пользователя
     */
    'uuid'?: string;
    /**
     * Email пользователя
     */
    'email'?: string;
    /**
     * Telegram ID пользователя
     */
    'telegram'?: number;
    /**
     * Флаг отключения уведомлений
     */
    'switchOffAlerts'?: boolean;
    /**
     * Тип отправки по умолчанию: true = email, false = telegram
     */
    'defaultSendType'?: boolean;
}
/**
 * Информация о модуле, от имени которого отправлены заказы
 */
export interface AiOrderModulesDTO {
    /**
     * ID модуля
     */
    'id'?: number;
    /**
     * Название модуля
     */
    'name'?: string;
}
/**
 * Расширенный запрос для AI, содержащий пользователя, модуль и список заказов
 */
export interface AiOrderRequest {
    'user'?: AiAppUserDTO;
    'module'?: AiOrderModulesDTO;
    /**
     * ID учётных данных пользователя (credential), связанных с модулем
     */
    'credentialId'?: number;
    /**
     * ID шаблона, который должен использоваться для генерации ответа
     */
    'templateId'?: number;
    'orders'?: OrderDTO;
}
/**
 * Запрос на создание шаблона
 */
export interface CreateTemplateRequest {
    /**
     * Название шаблона
     */
    'name'?: string;
    /**
     * UUID пользователя
     */
    'userUuid'?: string;
    /**
     * ID модуля
     */
    'moduleId'?: number;
    /**
     * HTML содержимое шаблона
     */
    'htmlTemplate'?: string;
}
/**
 * Информация о заказе, полученном с внешнего сайта
 */
export interface OrderDTO {
    /**
     * Заголовок заказа
     */
    'title'?: string;
    /**
     * Полное описание заказа
     */
    'message'?: string;
    /**
     * Ссылка на заказ
     */
    'link'?: string;
    /**
     * Дата и время публикации заказа
     */
    'dateTime'?: string;
    'price'?: PriceDTO;
    'sourceSite'?: SourceSiteDTO;
    /**
     * Название модуля, который обработал заказ
     */
    'moduleName'?: string;
    /**
     * Флаг: заказ открыт для всех пользователей
     */
    'openForAll'?: boolean;
    /**
     * Флаг валидности заказа (например, не удалён, не скрыт)
     */
    'validOrder'?: boolean;
}
/**
 * Информация о цене заказа
 */
export interface PriceDTO {
    /**
     * Цена в текстовом виде (как на сайте)
     */
    'price'?: string;
    /**
     * Цена в числовом виде (например рубли/доллары)
     */
    'value'?: number;
}
/**
 * Информация об источнике заказа: сайт, категория и подкатегория
 */
export interface SourceSiteDTO {
    /**
     * ID записи источника
     */
    'id'?: number;
    /**
     * ID сайта, откуда пришёл заказ
     */
    'source'?: number;
    /**
     * Название сайта-источника
     */
    'sourceName'?: string;
    /**
     * ID категории заказа
     */
    'category'?: number;
    /**
     * Название категории
     */
    'categoryName'?: string;
    /**
     * ID подкатегории заказа
     */
    'subCategory'?: number;
    /**
     * Название подкатегории
     */
    'subCategoryName'?: string;
}
/**
 * Ответ с информацией о шаблоне HTML для автоответов
 */
export interface TemplateResponse {
    /**
     * Название шаблона
     */
    'name'?: string;
    /**
     * Уникальный идентификатор шаблона
     */
    'id'?: number;
    /**
     * HTML содержимое шаблона
     */
    'htmlTemplate'?: string;
    /**
     * Дата создания шаблона
     */
    'createdAt'?: string;
}
export interface UploadPromptRequest {
    'file': File;
}

/**
 * AiPromptControllerApi - axios parameter creator
 */
export const AiPromptControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает ZIP-файл, содержащий все промты. Каждый промт — отдельный .txt файл. Имя файла = тип промта. 
         * @summary Экспортировать все промты в ZIP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportPrompts: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/prompts/export`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/octet-stream';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список DTO без текста промта — только служебная информация.
         * @summary Получить список всех промтов
         * @param {string} uUIDUserHeader 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPrompts: async (uUIDUserHeader: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uUIDUserHeader' is not null or undefined
            assertParamExists('listPrompts', 'uUIDUserHeader', uUIDUserHeader)
            const localVarPath = `/api/prompts/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            if (uUIDUserHeader != null) {
                localVarHeaderParameter['UUID-user-header'] = String(uUIDUserHeader);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Загружает текст промта из файла и сохраняет его. Если промт с таким типом уже существует — обновляет и увеличивает версию. Если нет — создаёт новый. 
         * @summary Загрузить или обновить промт
         * @param {number} module 
         * @param {string} name 
         * @param {UploadPromptRequest} [uploadPromptRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadPrompt: async (module: number, name: string, uploadPromptRequest?: UploadPromptRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'module' is not null or undefined
            assertParamExists('uploadPrompt', 'module', module)
            // verify required parameter 'name' is not null or undefined
            assertParamExists('uploadPrompt', 'name', name)
            const localVarPath = `/api/prompts/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (module !== undefined) {
                localVarQueryParameter['module'] = module;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadPromptRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AiPromptControllerApi - functional programming interface
 */
export const AiPromptControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AiPromptControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Возвращает ZIP-файл, содержащий все промты. Каждый промт — отдельный .txt файл. Имя файла = тип промта. 
         * @summary Экспортировать все промты в ZIP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportPrompts(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportPrompts(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiPromptControllerApi.exportPrompts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список DTO без текста промта — только служебная информация.
         * @summary Получить список всех промтов
         * @param {string} uUIDUserHeader 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPrompts(uUIDUserHeader: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPrompts(uUIDUserHeader, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiPromptControllerApi.listPrompts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Загружает текст промта из файла и сохраняет его. Если промт с таким типом уже существует — обновляет и увеличивает версию. Если нет — создаёт новый. 
         * @summary Загрузить или обновить промт
         * @param {number} module 
         * @param {string} name 
         * @param {UploadPromptRequest} [uploadPromptRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadPrompt(module: number, name: string, uploadPromptRequest?: UploadPromptRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadPrompt(module, name, uploadPromptRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiPromptControllerApi.uploadPrompt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AiPromptControllerApi - factory interface
 */
export const AiPromptControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AiPromptControllerApiFp(configuration)
    return {
        /**
         * Возвращает ZIP-файл, содержащий все промты. Каждый промт — отдельный .txt файл. Имя файла = тип промта. 
         * @summary Экспортировать все промты в ZIP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportPrompts(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.exportPrompts(options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список DTO без текста промта — только служебная информация.
         * @summary Получить список всех промтов
         * @param {string} uUIDUserHeader 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPrompts(uUIDUserHeader: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.listPrompts(uUIDUserHeader, options).then((request) => request(axios, basePath));
        },
        /**
         * Загружает текст промта из файла и сохраняет его. Если промт с таким типом уже существует — обновляет и увеличивает версию. Если нет — создаёт новый. 
         * @summary Загрузить или обновить промт
         * @param {number} module 
         * @param {string} name 
         * @param {UploadPromptRequest} [uploadPromptRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadPrompt(module: number, name: string, uploadPromptRequest?: UploadPromptRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.uploadPrompt(module, name, uploadPromptRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AiPromptControllerApi - object-oriented interface
 */
export class AiPromptControllerApi extends BaseAPI {
    /**
     * Возвращает ZIP-файл, содержащий все промты. Каждый промт — отдельный .txt файл. Имя файла = тип промта. 
     * @summary Экспортировать все промты в ZIP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportPrompts(options?: RawAxiosRequestConfig) {
        return AiPromptControllerApiFp(this.configuration).exportPrompts(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список DTO без текста промта — только служебная информация.
     * @summary Получить список всех промтов
     * @param {string} uUIDUserHeader 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listPrompts(uUIDUserHeader: string, options?: RawAxiosRequestConfig) {
        return AiPromptControllerApiFp(this.configuration).listPrompts(uUIDUserHeader, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Загружает текст промта из файла и сохраняет его. Если промт с таким типом уже существует — обновляет и увеличивает версию. Если нет — создаёт новый. 
     * @summary Загрузить или обновить промт
     * @param {number} module 
     * @param {string} name 
     * @param {UploadPromptRequest} [uploadPromptRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public uploadPrompt(module: number, name: string, uploadPromptRequest?: UploadPromptRequest, options?: RawAxiosRequestConfig) {
        return AiPromptControllerApiFp(this.configuration).uploadPrompt(module, name, uploadPromptRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AiReplyTemplateControllerApi - axios parameter creator
 */
export const AiReplyTemplateControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Создаёт новый HTML‑шаблон или обновляет существующий. Возвращает ID созданного/обновлённого шаблона.
         * @summary Создать или обновить шаблон
         * @param {CreateTemplateRequest} createTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate: async (createTemplateRequest: CreateTemplateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTemplateRequest' is not null or undefined
            assertParamExists('createOrUpdate', 'createTemplateRequest', createTemplateRequest)
            const localVarPath = `/api/templates/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTemplateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает true/false в зависимости от того, существует ли шаблон.
         * @summary Проверить существование шаблона
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exists: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('exists', 'id', id)
            const localVarPath = `/api/templates/{id}/exists`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает полную информацию о шаблоне.
         * @summary Получить шаблон по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplateById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTemplateById', 'id', id)
            const localVarPath = `/api/templates/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список всех шаблонов, созданных пользователем.
         * @summary Получить шаблоны пользователя
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplatesByUser: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('getTemplatesByUser', 'uuid', uuid)
            const localVarPath = `/api/templates/user/{uuid}`
                .replace('{uuid}', encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AiReplyTemplateControllerApi - functional programming interface
 */
export const AiReplyTemplateControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AiReplyTemplateControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Создаёт новый HTML‑шаблон или обновляет существующий. Возвращает ID созданного/обновлённого шаблона.
         * @summary Создать или обновить шаблон
         * @param {CreateTemplateRequest} createTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrUpdate(createTemplateRequest: CreateTemplateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrUpdate(createTemplateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiReplyTemplateControllerApi.createOrUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает true/false в зависимости от того, существует ли шаблон.
         * @summary Проверить существование шаблона
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exists(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exists(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiReplyTemplateControllerApi.exists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает полную информацию о шаблоне.
         * @summary Получить шаблон по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplateById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TemplateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTemplateById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiReplyTemplateControllerApi.getTemplateById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список всех шаблонов, созданных пользователем.
         * @summary Получить шаблоны пользователя
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTemplatesByUser(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TemplateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTemplatesByUser(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AiReplyTemplateControllerApi.getTemplatesByUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AiReplyTemplateControllerApi - factory interface
 */
export const AiReplyTemplateControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AiReplyTemplateControllerApiFp(configuration)
    return {
        /**
         * Создаёт новый HTML‑шаблон или обновляет существующий. Возвращает ID созданного/обновлённого шаблона.
         * @summary Создать или обновить шаблон
         * @param {CreateTemplateRequest} createTemplateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate(createTemplateRequest: CreateTemplateRequest, options?: RawAxiosRequestConfig): AxiosPromise<number> {
            return localVarFp.createOrUpdate(createTemplateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает true/false в зависимости от того, существует ли шаблон.
         * @summary Проверить существование шаблона
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exists(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.exists(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает полную информацию о шаблоне.
         * @summary Получить шаблон по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplateById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<TemplateResponse> {
            return localVarFp.getTemplateById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список всех шаблонов, созданных пользователем.
         * @summary Получить шаблоны пользователя
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTemplatesByUser(uuid: string, options?: RawAxiosRequestConfig): AxiosPromise<TemplateResponse> {
            return localVarFp.getTemplatesByUser(uuid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AiReplyTemplateControllerApi - object-oriented interface
 */
export class AiReplyTemplateControllerApi extends BaseAPI {
    /**
     * Создаёт новый HTML‑шаблон или обновляет существующий. Возвращает ID созданного/обновлённого шаблона.
     * @summary Создать или обновить шаблон
     * @param {CreateTemplateRequest} createTemplateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOrUpdate(createTemplateRequest: CreateTemplateRequest, options?: RawAxiosRequestConfig) {
        return AiReplyTemplateControllerApiFp(this.configuration).createOrUpdate(createTemplateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает true/false в зависимости от того, существует ли шаблон.
     * @summary Проверить существование шаблона
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exists(id: number, options?: RawAxiosRequestConfig) {
        return AiReplyTemplateControllerApiFp(this.configuration).exists(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает полную информацию о шаблоне.
     * @summary Получить шаблон по ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTemplateById(id: number, options?: RawAxiosRequestConfig) {
        return AiReplyTemplateControllerApiFp(this.configuration).getTemplateById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список всех шаблонов, созданных пользователем.
     * @summary Получить шаблоны пользователя
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTemplatesByUser(uuid: string, options?: RawAxiosRequestConfig) {
        return AiReplyTemplateControllerApiFp(this.configuration).getTemplatesByUser(uuid, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * OrdersControllerApi - axios parameter creator
 */
export const OrdersControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Принимает расширенный объект AiOrderRequest, содержащий: • список заказов, • данные пользователя, • данные модуля.  Используется для более точной обработки заказов с учётом контекста. 
         * @summary Получить заказы с дополнительной информацией (пользователь, модуль, шаблон и т.д.)
         * @param {AiOrderRequest} aiOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiveAiOrderRequest: async (aiOrderRequest: AiOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'aiOrderRequest' is not null or undefined
            assertParamExists('receiveAiOrderRequest', 'aiOrderRequest', aiOrderRequest)
            const localVarPath = `/ai/api/orders/context`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(aiOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Принимает список заказов (OrderDTO) и отправляет каждый заказ в AutoReplyPipeline. Используется для массовой обработки заказов без контекста пользователя. 
         * @summary Получить список заказов (устаревший метод - не используется или используется для тестов)
         * @param {Array<OrderDTO>} orderDTO 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        receiveOrders: async (orderDTO: Array<OrderDTO>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderDTO' is not null or undefined
            assertParamExists('receiveOrders', 'orderDTO', orderDTO)
            const localVarPath = `/ai/api/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(orderDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrdersControllerApi - functional programming interface
 */
export const OrdersControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrdersControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Принимает расширенный объект AiOrderRequest, содержащий: • список заказов, • данные пользователя, • данные модуля.  Используется для более точной обработки заказов с учётом контекста. 
         * @summary Получить заказы с дополнительной информацией (пользователь, модуль, шаблон и т.д.)
         * @param {AiOrderRequest} aiOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async receiveAiOrderRequest(aiOrderRequest: AiOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.receiveAiOrderRequest(aiOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrdersControllerApi.receiveAiOrderRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Принимает список заказов (OrderDTO) и отправляет каждый заказ в AutoReplyPipeline. Используется для массовой обработки заказов без контекста пользователя. 
         * @summary Получить список заказов (устаревший метод - не используется или используется для тестов)
         * @param {Array<OrderDTO>} orderDTO 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async receiveOrders(orderDTO: Array<OrderDTO>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.receiveOrders(orderDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrdersControllerApi.receiveOrders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrdersControllerApi - factory interface
 */
export const OrdersControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrdersControllerApiFp(configuration)
    return {
        /**
         * Принимает расширенный объект AiOrderRequest, содержащий: • список заказов, • данные пользователя, • данные модуля.  Используется для более точной обработки заказов с учётом контекста. 
         * @summary Получить заказы с дополнительной информацией (пользователь, модуль, шаблон и т.д.)
         * @param {AiOrderRequest} aiOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiveAiOrderRequest(aiOrderRequest: AiOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.receiveAiOrderRequest(aiOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Принимает список заказов (OrderDTO) и отправляет каждый заказ в AutoReplyPipeline. Используется для массовой обработки заказов без контекста пользователя. 
         * @summary Получить список заказов (устаревший метод - не используется или используется для тестов)
         * @param {Array<OrderDTO>} orderDTO 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        receiveOrders(orderDTO: Array<OrderDTO>, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.receiveOrders(orderDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrdersControllerApi - object-oriented interface
 */
export class OrdersControllerApi extends BaseAPI {
    /**
     * Принимает расширенный объект AiOrderRequest, содержащий: • список заказов, • данные пользователя, • данные модуля.  Используется для более точной обработки заказов с учётом контекста. 
     * @summary Получить заказы с дополнительной информацией (пользователь, модуль, шаблон и т.д.)
     * @param {AiOrderRequest} aiOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public receiveAiOrderRequest(aiOrderRequest: AiOrderRequest, options?: RawAxiosRequestConfig) {
        return OrdersControllerApiFp(this.configuration).receiveAiOrderRequest(aiOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Принимает список заказов (OrderDTO) и отправляет каждый заказ в AutoReplyPipeline. Используется для массовой обработки заказов без контекста пользователя. 
     * @summary Получить список заказов (устаревший метод - не используется или используется для тестов)
     * @param {Array<OrderDTO>} orderDTO 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    public receiveOrders(orderDTO: Array<OrderDTO>, options?: RawAxiosRequestConfig) {
        return OrdersControllerApiFp(this.configuration).receiveOrders(orderDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



