server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*.log

  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_path']
        target_label: '__path__'
      - target_label: 'job'
        replacement: 'containers'

  # НОВОЕ: TCP вход для замены Logstash
  - job_name: tcp-logs
    syslog:
      listen_address: 0.0.0.0:5000
      idle_timeout: 60s
      labels:
        job: "tcp-logs"
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
      - labels:
          level:
      - static_labels:
          tag: "manningPublications"
