server.port=8011
spring.application.name=alert-job-config
management.endpoints.web.exposure.include=*
spring.profiles.active=dev,native
encrypt.key=${encrypt_key:test}
spring.cloud.config.server.git.uri=https://github.com/gdevby/alert-job-config.git
