#spring.profiles.active=dev,native
#you can add this param to local profile running and set param native,dev to get configuration from local directory without pushing changes
# for windows 
#spring.cloud.config.server.native.search-locations=file:/e:/Programming/Java_EE/alert-job-config-repo/
#for linux
#spring.cloud.config.server.native.search-locations=file:///....../alert-job-config-repo
#for mounting in docker when there is some data in that directory
#spring.cloud.config.server.native.search-locations=file:///alert-job-config-repo"
