--  https://2cyr.com/decode/?lang=ru
-- script SIMPLE to '/tmp/t.sql'
-- H2 2.1.214; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '40e1ca6958336681' HASH 'e8109e3b57539c4edee7702e7895f35b5c2970fab8a67bf90f8bbdda9c4be9fe' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."ORDER_LINKS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "CREATED_DATE" TIMESTAMP,
    "LINKS" CHARACTER VARYING(255),
    "CATEGORY_ID" BIGINT,
    "SUB_CATEGORY_ID" BIGINT
);               
ALTER TABLE "PUBLIC"."ORDER_LINKS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_LINKS;              
CREATE MEMORY TABLE "PUBLIC"."FL_CATEGORY"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NATIVE_LOC_NAME" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."FL_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");   
-- 20 +/- SELECT COUNT(*) FROM PUBLIC.FL_CATEGORY;             
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(1, U&'\041c\0435\043d\0435\0434\0436\043c\0435\043d\0442');          
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(2, U&'\0420\0430\0437\0440\0430\0431\043e\0442\043a\0430 \0441\0430\0439\0442\043e\0432');           
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(3, U&'\0414\0438\0437\0430\0439\043d \0438 \0410\0440\0442');        
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(5, U&'\041f\0440\043e\0433\0440\0430\043c\043c\0438\0440\043e\0432\0430\043d\0438\0435');            
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(6, U&'\041e\043f\0442\0438\043c\0438\0437\0430\0446\0438\044f (SEO)');               
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(7, U&'\041f\0435\0440\0435\0432\043e\0434\044b');    
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(8, U&'\0422\0435\043a\0441\0442\044b');              
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(9, U&'3D \0413\0440\0430\0444\0438\043a\0430');      
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(10, U&'\0424\043e\0442\043e\0433\0440\0430\0444\0438\044f');         
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(11, U&'\0410\0443\0434\0438\043e/\0412\0438\0434\0435\043e');        
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(12, U&'\0420\0435\043a\043b\0430\043c\0430 \0438 \041c\0430\0440\043a\0435\0442\0438\043d\0433');    
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(13, U&'\0410\0443\0442\0441\043e\0440\0441\0438\043d\0433 \0438 \043a\043e\043d\0441\0430\043b\0442\0438\043d\0433');
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(14, U&'\0410\0440\0445\0438\0442\0435\043a\0442\0443\0440\0430/\0418\043d\0442\0435\0440\044c\0435\0440');           
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(16, U&'\0420\0430\0437\0440\0430\0431\043e\0442\043a\0430 \0438\0433\0440');         
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(17, U&'\041f\043e\043b\0438\0433\0440\0430\0444\0438\044f');         
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(19, U&'\0410\043d\0438\043c\0430\0446\0438\044f \0438 \0444\043b\0435\0448');        
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(20, U&'\0418\043d\0436\0438\043d\0438\0440\0438\043d\0433');         
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(22, U&'\041e\0431\0443\0447\0435\043d\0438\0435 \0438 \043a\043e\043d\0441\0443\043b\044c\0442\0430\0446\0438\0438');
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(23, U&'\041c\043e\0431\0438\043b\044c\043d\044b\0435 \043f\0440\0438\043b\043e\0436\0435\043d\0438\044f');           
INSERT INTO "PUBLIC"."FL_CATEGORY" VALUES(24, U&'\0421\0435\0442\0438 \0438 \0438\043d\0444\043e\0441\0438\0441\0442\0435\043c\044b');         

       
CREATE MEMORY TABLE "PUBLIC"."SITE_SOURCE_JOB"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "PARSEDURI" CHARACTER VARYING(255),
    "ACTIVE" BOOLEAN NOT NULL,
    "PARSE" BOOLEAN NOT NULL
);            
ALTER TABLE "PUBLIC"."SITE_SOURCE_JOB" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");               
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.SITE_SOURCE_JOB;          
INSERT INTO "PUBLIC"."SITE_SOURCE_JOB" VALUES(1, 'FLRU', 'https://www.fl.ru/projects/', TRUE, TRUE); 
--INSERT INTO "PUBLIC"."SITE_SOURCE_JOB" VALUES(2, 'HABR', 'https://freelance.habr.com/tasks', TRUE, TRUE); not in use anymore    


-- ===========================
-- H2 Database Initialization LLM
-- ===========================

-- ===========================
-- llm_user
-- ===========================
CREATE TABLE IF NOT EXISTS llm_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(255)
);

-- ===========================
-- ai_prompt
-- ===========================
CREATE TABLE IF NOT EXISTS ai_prompt (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type VARCHAR(100) NOT NULL,
    name VARCHAR(512),
    prompt_text CLOB NOT NULL,
    version INT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ===========================
-- ai_reply_template
-- ===========================
CREATE TABLE IF NOT EXISTS ai_reply_template (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(512),
    user_id BIGINT,
    module_id BIGINT,
    html_template CLOB,
    CONSTRAINT fk_ai_reply_template_user 
        FOREIGN KEY (user_id) REFERENCES llm_user(id) ON DELETE SET NULL
);

-- ===========================
-- DEFAULT PROMPT
-- ===========================
INSERT INTO ai_prompt (type, prompt_text, version, created_at, updated_at)
SELECT 
    'DEFAULT',
    'Ты — экспертный аналитик фриланс-заказов и профильный специалист по разработке решений под заданную категорию и подкатегорию.\nТвоя задача — уверенно и аргументированно определить релевантность заказа, объяснить логику классификации и сформировать профессиональный автоответ.\n\nАнализируй заказ строго в контексте данных парсинга.\n\nЗаказ:\nДанные заказа:\nЗаголовок: %s\nОписание: %s\nЦена (текст): %s\nЦена (число): %s\nСсылка: %s\nДата: %s\nСайт: %s\nКатегория: %s\nПодкатегория: %s\nКлючевые слова: %s\n\nШаблон письма, который нужно использовать при формировании поля reply:\n%s\n\nВажно: если в заказе указана цена или бюджет, игнорируй любые части шаблона письма, которые предлагают уточнить бюджет. В таких случаях НЕ спрашивай бюджет повторно.\nЕсли цена отсутствует — можно попросить уточнить бюджет.\n\nОБЩИЕ ТРЕБОВАНИЯ К АНАЛИЗУ:\n\nЕсли в заказе указана цена или бюджет (в любом виде: текстом, числом, диапазоном), НИКОГДА не спрашивай бюджет повторно в поле reply.\nЕсли цена отсутствует — можно попросить уточнить бюджет.\n\n1. shouldReply — логичное и уверенное решение: отвечать или нет.\n   true — заказ релевантен указанной категории/подкатегории.\n   false — заказ нерелевантен.\n\n2. confidence — честная оценка уверенности (0.0–1.0).\n\n3. reason — краткое, но уверенное объяснение, почему принято решение.\n\n4. reply — профессиональный, уверенный автоответ, без извинений, сомнений и воды.\n   Структура ответа:\n   - 1–2 предложения: подтверждение компетенции и понимания задачи.\n   - 1–3 предложения: уточнение ключевых деталей (требования, объём, стиль, сроки, бюджет).\n   - 1 предложение: чёткий call-to-action.\nЕсли заказ содержит мало информации (короткий заголовок, пустое описание, отсутствие технических деталей, требований, объёма работ, сроков или контекста), ОБЯЗАТЕЛЬНО добавь в поле reply 1–2 уточняющих вопроса.\nЕсли в заказе указаны сроки — НИКОГДА не спрашивай сроки повторно.\n\nУточняющие вопросы должны быть конкретными, по делу, связанными с типом проекта, не более 2 штук.\nЕсли информации достаточно — НЕ задавай уточняющих вопросов.\n\n5. matchedKeywords — какие ключевые слова реально найдены.\n6. missedKeywords — какие ожидались, но не найдены.\n7. categoryMatchReason — почему заказ относится к категории.\n8. subcategoryMatchReason — почему относится к подкатегории.\n\nСТИЛЬ:\n- Пиши строго и уверенно.\n- Не используй markdown.\n- Пиши на языке заказа.\n\nВерни ТОЛЬКО JSON:\n{\n  \"shouldReply\": true/false,\n  \"confidence\": 0.0-1.0,\n  \"reason\": \"...\",\n  \"reply\": \"...\",\n  \"matchedKeywords\": [...],\n  \"missedKeywords\": [...],\n  \"categoryMatchReason\": \"...\",\n  \"subcategoryMatchReason\": \"...\"\n}\n\nПоле reply должно быть одной строкой. Переносы — только через \\n.\n\nТребования к confidence:\n- строго 0.0–1.0\n- нельзя проценты\n- нельзя целые числа\n\nЕсли в шаблоне письма есть %auto_generated_text%, замени его на сгенерированный текст.',
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM ai_prompt WHERE type = 'DEFAULT'
);

-- ===========================
-- DEFAULT TEMPLATE
-- ===========================
INSERT INTO ai_reply_template (name, user_id, module_id, html_template)
SELECT 
    'DEFAULT_TEMPLATE',
    NULL,
    NULL,
    'Добрый день!\n\nНе беру предоплату, работаю только поэтапно или по достижению конечного результата.\n\nМогу вас бесплатно проконсультировать для обсуждения всех деталей и подробностей проекта, прежде чем взяться за работу.\n\nКонтакты:\n• Телеграм: https://t.me/grovedevconsult\n\nУсловия сотрудничества:\n• Бесплатная консультация - обсуждение деталей, оценка стоимости и сроков работы.\n• Безопасность - заключение договора, гарантия выполнения ваших задач.'
WHERE NOT EXISTS (
    SELECT 1 FROM ai_reply_template WHERE name = 'DEFAULT_TEMPLATE'
);       
