/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AccountTemplateBinding {
    'id'?: number;
    'moduleId'?: number;
    'accountId'?: number;
    'templateId'?: number;
    'active'?: boolean;
    'createdAt'?: string;
    'updatedAt'?: string;
}
export interface BindingResponse {
    'id'?: number;
    'accountName'?: string;
    'templateName'?: string;
    'createdAt'?: string;
    'active'?: boolean;
}
export interface CategoryChangeDTO {
    'siteSourceId'?: number;
    'siteName'?: string;
    'diff'?: CategoryDiffDTO;
}
export interface CategoryChangeListDTO {
    'changes'?: Array<CategoryChangeDTO>;
}
export interface CategoryDTO {
    'id'?: number;
    'name'?: string;
    'subcategories'?: Array<SubcategoryDTO>;
}
export interface CategoryDiffDTO {
    'newCategories'?: Array<CategoryDTO>;
    'removedCategories'?: Array<CategoryDTO>;
    'movedCategories'?: Array<CategoryMoveDTO>;
    'newSubcategories'?: Array<SubcategoryWithParentDTO>;
    'removedSubcategories'?: Array<SubcategoryWithParentDTO>;
    'movedSubcategories'?: Array<SubcategoryMoveDTO>;
}
export interface CategoryMoveDTO {
    'oldCategory'?: CategoryDTO;
    'newCategory'?: CategoryDTO;
}
export interface CleanupRequest {
    'siteId'?: number;
    'siteName'?: string;
    'categories'?: Array<ParserCategoryDTO>;
    'mode'?: CleanupRequestModeEnum;
}

export const CleanupRequestModeEnum = {
    TypeNotification: 'TYPE_NOTIFICATION',
    TypeFull: 'TYPE_FULL',
} as const;

export type CleanupRequestModeEnum = typeof CleanupRequestModeEnum[keyof typeof CleanupRequestModeEnum];

export interface OrderDTO {
    'title'?: string;
    'message'?: string;
    'link'?: string;
    'dateTime'?: string;
    'price'?: PriceDTO;
    'sourceSite'?: SourceSiteDTO;
    'moduleName'?: string;
    'openForAll'?: boolean;
    'validOrder'?: boolean;
}
export interface ParserCategoryDTO {
    'categoryId'?: number;
    'categoryName'?: string;
    'subCategoryId'?: number;
    'subCategoryName'?: string;
}
export interface PriceDTO {
    'price'?: string;
    'value'?: number;
}
export interface SourceSiteDTO {
    'id'?: number;
    'source'?: number;
    'sourceName'?: string;
    'category'?: number;
    'categoryName'?: string;
    'subCategory'?: number;
    'subCategoryName'?: string;
}
export interface SubcategoryDTO {
    'id'?: number;
    'name'?: string;
}
export interface SubcategoryMoveDTO {
    'oldParentId'?: number;
    'oldParentName'?: string;
    'newParentId'?: number;
    'newParentName'?: string;
    'subcategory'?: SubcategoryDTO;
}
export interface SubcategoryWithParentDTO {
    'parentId'?: number;
    'parentName'?: string;
    'subcategory'?: SubcategoryDTO;
}
export interface UserCredentialEncrypted {
    'name'?: string;
    'login'?: string;
    'passwordEncrypted'?: string;
}
export interface UserCredentialRequest {
    'name'?: string;
    'userUuid'?: string;
    'siteId'?: number;
    'moduleId'?: number;
    'login'?: string;
    'password'?: string;
}
export interface UserSiteCredential {
    'id'?: number;
    'name'?: string;
    'siteId'?: number;
    'userUuid'?: string;
    'moduleId'?: number;
    'login'?: string;
    'passwordEncrypted'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
}
export interface UserSiteCredentialShortResponse {
    'id'?: number;
    'name'?: string;
    'login'?: string;
    'createdAt'?: string;
}

/**
 * AccountTemplateBindingsApi - axios parameter creator
 */
export const AccountTemplateBindingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Удаляет привязку по её ID.
         * @summary Удалить привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('_delete', 'id', id)
            const localVarPath = `/api/bindings/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Устанавливает статус активности = true для указанной привязки.
         * @summary Активировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('activate', 'id', id)
            const localVarPath = `/api/bindings/{id}/activate`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Создаёт связь между модулем, аккаунтом и шаблоном с указанием активности.
         * @summary Создать новую привязку
         * @param {number} moduleId 
         * @param {number} accountId 
         * @param {number} templateId 
         * @param {boolean} [active] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (moduleId: number, accountId: number, templateId: number, active?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'moduleId' is not null or undefined
            assertParamExists('create', 'moduleId', moduleId)
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('create', 'accountId', accountId)
            // verify required parameter 'templateId' is not null or undefined
            assertParamExists('create', 'templateId', templateId)
            const localVarPath = `/api/bindings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (moduleId !== undefined) {
                localVarQueryParameter['moduleId'] = moduleId;
            }

            if (accountId !== undefined) {
                localVarQueryParameter['accountId'] = accountId;
            }

            if (templateId !== undefined) {
                localVarQueryParameter['templateId'] = templateId;
            }

            if (active !== undefined) {
                localVarQueryParameter['active'] = active;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Устанавливает статус активности = false для указанной привязки.
         * @summary Деактивировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deactivate', 'id', id)
            const localVarPath = `/api/bindings/{id}/deactivate`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список привязок для конкретного пользователя (по UUID) и модуля. В случае ошибки возвращает текстовое сообщение.
         * @summary Получить все привязки для пользователя и модуля
         * @param {string} uuid 
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllBindingsForUser: async (uuid: string, moduleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('getAllBindingsForUser', 'uuid', uuid)
            // verify required parameter 'moduleId' is not null or undefined
            assertParamExists('getAllBindingsForUser', 'moduleId', moduleId)
            const localVarPath = `/api/bindings/user/{uuid}/module/{moduleId}`
                .replace('{uuid}', encodeURIComponent(String(uuid)))
                .replace('{moduleId}', encodeURIComponent(String(moduleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список всех привязок, относящихся к указанному модулю.
         * @summary Получить все привязки для модуля
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByModule: async (moduleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'moduleId' is not null or undefined
            assertParamExists('getByModule', 'moduleId', moduleId)
            const localVarPath = `/api/bindings/{moduleId}`
                .replace('{moduleId}', encodeURIComponent(String(moduleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Устанавливает произвольный статус активности (true/false) для привязки.
         * @summary Установить статус активности
         * @param {number} id 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setActive: async (id: number, active: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('setActive', 'id', id)
            // verify required parameter 'active' is not null or undefined
            assertParamExists('setActive', 'active', active)
            const localVarPath = `/api/bindings/{id}/active`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (active !== undefined) {
                localVarQueryParameter['active'] = active;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Изменяет параметры привязки по её ID.
         * @summary Обновить существующую привязку
         * @param {number} id 
         * @param {number} moduleId 
         * @param {number} accountId 
         * @param {number} templateId 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (id: number, moduleId: number, accountId: number, templateId: number, active: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('update', 'id', id)
            // verify required parameter 'moduleId' is not null or undefined
            assertParamExists('update', 'moduleId', moduleId)
            // verify required parameter 'accountId' is not null or undefined
            assertParamExists('update', 'accountId', accountId)
            // verify required parameter 'templateId' is not null or undefined
            assertParamExists('update', 'templateId', templateId)
            // verify required parameter 'active' is not null or undefined
            assertParamExists('update', 'active', active)
            const localVarPath = `/api/bindings/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (moduleId !== undefined) {
                localVarQueryParameter['moduleId'] = moduleId;
            }

            if (accountId !== undefined) {
                localVarQueryParameter['accountId'] = accountId;
            }

            if (templateId !== undefined) {
                localVarQueryParameter['templateId'] = templateId;
            }

            if (active !== undefined) {
                localVarQueryParameter['active'] = active;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountTemplateBindingsApi - functional programming interface
 */
export const AccountTemplateBindingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountTemplateBindingsApiAxiosParamCreator(configuration)
    return {
        /**
         * Удаляет привязку по её ID.
         * @summary Удалить привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async _delete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator._delete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi._delete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Устанавливает статус активности = true для указанной привязки.
         * @summary Активировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTemplateBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.activate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Создаёт связь между модулем, аккаунтом и шаблоном с указанием активности.
         * @summary Создать новую привязку
         * @param {number} moduleId 
         * @param {number} accountId 
         * @param {number} templateId 
         * @param {boolean} [active] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(moduleId: number, accountId: number, templateId: number, active?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTemplateBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(moduleId, accountId, templateId, active, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Устанавливает статус активности = false для указанной привязки.
         * @summary Деактивировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deactivate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTemplateBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deactivate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.deactivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список привязок для конкретного пользователя (по UUID) и модуля. В случае ошибки возвращает текстовое сообщение.
         * @summary Получить все привязки для пользователя и модуля
         * @param {string} uuid 
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllBindingsForUser(uuid: string, moduleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllBindingsForUser(uuid, moduleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.getAllBindingsForUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список всех привязок, относящихся к указанному модулю.
         * @summary Получить все привязки для модуля
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByModule(moduleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTemplateBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByModule(moduleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.getByModule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Устанавливает произвольный статус активности (true/false) для привязки.
         * @summary Установить статус активности
         * @param {number} id 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setActive(id: number, active: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTemplateBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setActive(id, active, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.setActive']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Изменяет параметры привязки по её ID.
         * @summary Обновить существующую привязку
         * @param {number} id 
         * @param {number} moduleId 
         * @param {number} accountId 
         * @param {number} templateId 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(id: number, moduleId: number, accountId: number, templateId: number, active: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTemplateBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(id, moduleId, accountId, templateId, active, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountTemplateBindingsApi - factory interface
 */
export const AccountTemplateBindingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountTemplateBindingsApiFp(configuration)
    return {
        /**
         * Удаляет привязку по её ID.
         * @summary Удалить привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp._delete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Устанавливает статус активности = true для указанной привязки.
         * @summary Активировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AccountTemplateBinding> {
            return localVarFp.activate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Создаёт связь между модулем, аккаунтом и шаблоном с указанием активности.
         * @summary Создать новую привязку
         * @param {number} moduleId 
         * @param {number} accountId 
         * @param {number} templateId 
         * @param {boolean} [active] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(moduleId: number, accountId: number, templateId: number, active?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<AccountTemplateBinding> {
            return localVarFp.create(moduleId, accountId, templateId, active, options).then((request) => request(axios, basePath));
        },
        /**
         * Устанавливает статус активности = false для указанной привязки.
         * @summary Деактивировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AccountTemplateBinding> {
            return localVarFp.deactivate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список привязок для конкретного пользователя (по UUID) и модуля. В случае ошибки возвращает текстовое сообщение.
         * @summary Получить все привязки для пользователя и модуля
         * @param {string} uuid 
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllBindingsForUser(uuid: string, moduleId: number, options?: RawAxiosRequestConfig): AxiosPromise<BindingResponse> {
            return localVarFp.getAllBindingsForUser(uuid, moduleId, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список всех привязок, относящихся к указанному модулю.
         * @summary Получить все привязки для модуля
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByModule(moduleId: number, options?: RawAxiosRequestConfig): AxiosPromise<AccountTemplateBinding> {
            return localVarFp.getByModule(moduleId, options).then((request) => request(axios, basePath));
        },
        /**
         * Устанавливает произвольный статус активности (true/false) для привязки.
         * @summary Установить статус активности
         * @param {number} id 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setActive(id: number, active: boolean, options?: RawAxiosRequestConfig): AxiosPromise<AccountTemplateBinding> {
            return localVarFp.setActive(id, active, options).then((request) => request(axios, basePath));
        },
        /**
         * Изменяет параметры привязки по её ID.
         * @summary Обновить существующую привязку
         * @param {number} id 
         * @param {number} moduleId 
         * @param {number} accountId 
         * @param {number} templateId 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(id: number, moduleId: number, accountId: number, templateId: number, active: boolean, options?: RawAxiosRequestConfig): AxiosPromise<AccountTemplateBinding> {
            return localVarFp.update(id, moduleId, accountId, templateId, active, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountTemplateBindingsApi - object-oriented interface
 */
export class AccountTemplateBindingsApi extends BaseAPI {
    /**
     * Удаляет привязку по её ID.
     * @summary Удалить привязку
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public _delete(id: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration)._delete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Устанавливает статус активности = true для указанной привязки.
     * @summary Активировать привязку
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public activate(id: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).activate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Создаёт связь между модулем, аккаунтом и шаблоном с указанием активности.
     * @summary Создать новую привязку
     * @param {number} moduleId 
     * @param {number} accountId 
     * @param {number} templateId 
     * @param {boolean} [active] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(moduleId: number, accountId: number, templateId: number, active?: boolean, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).create(moduleId, accountId, templateId, active, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Устанавливает статус активности = false для указанной привязки.
     * @summary Деактивировать привязку
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deactivate(id: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).deactivate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список привязок для конкретного пользователя (по UUID) и модуля. В случае ошибки возвращает текстовое сообщение.
     * @summary Получить все привязки для пользователя и модуля
     * @param {string} uuid 
     * @param {number} moduleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllBindingsForUser(uuid: string, moduleId: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).getAllBindingsForUser(uuid, moduleId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список всех привязок, относящихся к указанному модулю.
     * @summary Получить все привязки для модуля
     * @param {number} moduleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getByModule(moduleId: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).getByModule(moduleId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Устанавливает произвольный статус активности (true/false) для привязки.
     * @summary Установить статус активности
     * @param {number} id 
     * @param {boolean} active 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setActive(id: number, active: boolean, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).setActive(id, active, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Изменяет параметры привязки по её ID.
     * @summary Обновить существующую привязку
     * @param {number} id 
     * @param {number} moduleId 
     * @param {number} accountId 
     * @param {number} templateId 
     * @param {boolean} active 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(id: number, moduleId: number, accountId: number, templateId: number, active: boolean, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).update(id, moduleId, accountId, templateId, active, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AppUserControllerApi - axios parameter creator
 */
export const AppUserControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByUuid: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('getUserByUuid', 'uuid', uuid)
            const localVarPath = `/api/users/{uuid}`
                .replace('{uuid}', encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppUserControllerApi - functional programming interface
 */
export const AppUserControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppUserControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserByUuid(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserByUuid(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppUserControllerApi.getUserByUuid']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppUserControllerApi - factory interface
 */
export const AppUserControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppUserControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByUuid(uuid: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.getUserByUuid(uuid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppUserControllerApi - object-oriented interface
 */
export class AppUserControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserByUuid(uuid: string, options?: RawAxiosRequestConfig) {
        return AppUserControllerApiFp(this.configuration).getUserByUuid(uuid, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CategoryChangeControllerApi - axios parameter creator
 */
export const CategoryChangeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CategoryChangeListDTO} categoryChangeListDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiveChanges: async (categoryChangeListDTO: CategoryChangeListDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'categoryChangeListDTO' is not null or undefined
            assertParamExists('receiveChanges', 'categoryChangeListDTO', categoryChangeListDTO)
            const localVarPath = `/category/changes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(categoryChangeListDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CategoryChangeControllerApi - functional programming interface
 */
export const CategoryChangeControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CategoryChangeControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CategoryChangeListDTO} categoryChangeListDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async receiveChanges(categoryChangeListDTO: CategoryChangeListDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.receiveChanges(categoryChangeListDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CategoryChangeControllerApi.receiveChanges']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CategoryChangeControllerApi - factory interface
 */
export const CategoryChangeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CategoryChangeControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {CategoryChangeListDTO} categoryChangeListDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiveChanges(categoryChangeListDTO: CategoryChangeListDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.receiveChanges(categoryChangeListDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CategoryChangeControllerApi - object-oriented interface
 */
export class CategoryChangeControllerApi extends BaseAPI {
    /**
     * 
     * @param {CategoryChangeListDTO} categoryChangeListDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public receiveChanges(categoryChangeListDTO: CategoryChangeListDTO, options?: RawAxiosRequestConfig) {
        return CategoryChangeControllerApiFp(this.configuration).receiveChanges(categoryChangeListDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CleanupControllerApi - axios parameter creator
 */
export const CleanupControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CleanupRequest} cleanupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cleanupParserSourceForSite: async (cleanupRequest: CleanupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cleanupRequest' is not null or undefined
            assertParamExists('cleanupParserSourceForSite', 'cleanupRequest', cleanupRequest)
            const localVarPath = `/api/cleanup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cleanupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CleanupControllerApi - functional programming interface
 */
export const CleanupControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CleanupControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CleanupRequest} cleanupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cleanupParserSourceForSite(cleanupRequest: CleanupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cleanupParserSourceForSite(cleanupRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CleanupControllerApi.cleanupParserSourceForSite']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CleanupControllerApi - factory interface
 */
export const CleanupControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CleanupControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {CleanupRequest} cleanupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cleanupParserSourceForSite(cleanupRequest: CleanupRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.cleanupParserSourceForSite(cleanupRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CleanupControllerApi - object-oriented interface
 */
export class CleanupControllerApi extends BaseAPI {
    /**
     * 
     * @param {CleanupRequest} cleanupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cleanupParserSourceForSite(cleanupRequest: CleanupRequest, options?: RawAxiosRequestConfig) {
        return CleanupControllerApiFp(this.configuration).cleanupParserSourceForSite(cleanupRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * OrdersControllerApi - axios parameter creator
 */
export const OrdersControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} site 
         * @param {Array<OrderDTO>} orderDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrders: async (site: string, orderDTO: Array<OrderDTO>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'site' is not null or undefined
            assertParamExists('createOrders', 'site', site)
            // verify required parameter 'orderDTO' is not null or undefined
            assertParamExists('createOrders', 'orderDTO', orderDTO)
            const localVarPath = `/api/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (site !== undefined) {
                localVarQueryParameter['site'] = site;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(orderDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAutoReplyStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/orders/autoreply-status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrdersControllerApi - functional programming interface
 */
export const OrdersControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrdersControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} site 
         * @param {Array<OrderDTO>} orderDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrders(site: string, orderDTO: Array<OrderDTO>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrders(site, orderDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrdersControllerApi.createOrders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAutoReplyStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAutoReplyStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrdersControllerApi.getAutoReplyStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrdersControllerApi - factory interface
 */
export const OrdersControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrdersControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {string} site 
         * @param {Array<OrderDTO>} orderDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrders(site: string, orderDTO: Array<OrderDTO>, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.createOrders(site, orderDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAutoReplyStatus(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.getAutoReplyStatus(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrdersControllerApi - object-oriented interface
 */
export class OrdersControllerApi extends BaseAPI {
    /**
     * 
     * @param {string} site 
     * @param {Array<OrderDTO>} orderDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOrders(site: string, orderDTO: Array<OrderDTO>, options?: RawAxiosRequestConfig) {
        return OrdersControllerApiFp(this.configuration).createOrders(site, orderDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAutoReplyStatus(options?: RawAxiosRequestConfig) {
        return OrdersControllerApiFp(this.configuration).getAutoReplyStatus(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserCredentialsApi - axios parameter creator
 */
export const UserCredentialsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Создаёт новую запись учётных данных или обновляет существующую. Возвращает сохранённый объект UserSiteCredential.
         * @summary Создать или обновить учётные данные
         * @param {UserCredentialRequest} userCredentialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate: async (userCredentialRequest: UserCredentialRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCredentialRequest' is not null or undefined
            assertParamExists('createOrUpdate', 'userCredentialRequest', userCredentialRequest)
            const localVarPath = `/api/credentials/create-or-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCredentialRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список всех учётных данных для указанного пользователя (по UUID). Возвращается сокращённая информация (ID, имя, логин, дата создания).
         * @summary Получить все учётные данные пользователя
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUserCredentials: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('getAllUserCredentials', 'uuid', uuid)
            const localVarPath = `/api/credentials/user/{uuid}/all`
                .replace('{uuid}', encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанных пользователя, сайта и модуля.
         * @summary Получить зашифрованные учётные данные
         * @param {string} userUuid 
         * @param {number} siteId 
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEncrypted: async (userUuid: string, siteId: number, moduleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userUuid' is not null or undefined
            assertParamExists('getEncrypted', 'userUuid', userUuid)
            // verify required parameter 'siteId' is not null or undefined
            assertParamExists('getEncrypted', 'siteId', siteId)
            // verify required parameter 'moduleId' is not null or undefined
            assertParamExists('getEncrypted', 'moduleId', moduleId)
            const localVarPath = `/api/credentials/get-encrypted`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userUuid !== undefined) {
                localVarQueryParameter['userUuid'] = userUuid;
            }

            if (siteId !== undefined) {
                localVarQueryParameter['siteId'] = siteId;
            }

            if (moduleId !== undefined) {
                localVarQueryParameter['moduleId'] = moduleId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанного ID учётной записи.
         * @summary Получить зашифрованные учётные данные по ID
         * @param {number} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEncryptedById: async (credentialId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('getEncryptedById', 'credentialId', credentialId)
            const localVarPath = `/api/credentials/get-encrypted-by-id`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (credentialId !== undefined) {
                localVarQueryParameter['credentialId'] = credentialId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserCredentialsApi - functional programming interface
 */
export const UserCredentialsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserCredentialsApiAxiosParamCreator(configuration)
    return {
        /**
         * Создаёт новую запись учётных данных или обновляет существующую. Возвращает сохранённый объект UserSiteCredential.
         * @summary Создать или обновить учётные данные
         * @param {UserCredentialRequest} userCredentialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrUpdate(userCredentialRequest: UserCredentialRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSiteCredential>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrUpdate(userCredentialRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserCredentialsApi.createOrUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список всех учётных данных для указанного пользователя (по UUID). Возвращается сокращённая информация (ID, имя, логин, дата создания).
         * @summary Получить все учётные данные пользователя
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllUserCredentials(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSiteCredentialShortResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllUserCredentials(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserCredentialsApi.getAllUserCredentials']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанных пользователя, сайта и модуля.
         * @summary Получить зашифрованные учётные данные
         * @param {string} userUuid 
         * @param {number} siteId 
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEncrypted(userUuid: string, siteId: number, moduleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserCredentialEncrypted>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEncrypted(userUuid, siteId, moduleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserCredentialsApi.getEncrypted']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанного ID учётной записи.
         * @summary Получить зашифрованные учётные данные по ID
         * @param {number} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEncryptedById(credentialId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserCredentialEncrypted>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEncryptedById(credentialId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserCredentialsApi.getEncryptedById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserCredentialsApi - factory interface
 */
export const UserCredentialsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserCredentialsApiFp(configuration)
    return {
        /**
         * Создаёт новую запись учётных данных или обновляет существующую. Возвращает сохранённый объект UserSiteCredential.
         * @summary Создать или обновить учётные данные
         * @param {UserCredentialRequest} userCredentialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate(userCredentialRequest: UserCredentialRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserSiteCredential> {
            return localVarFp.createOrUpdate(userCredentialRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список всех учётных данных для указанного пользователя (по UUID). Возвращается сокращённая информация (ID, имя, логин, дата создания).
         * @summary Получить все учётные данные пользователя
         * @param {string} uuid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUserCredentials(uuid: string, options?: RawAxiosRequestConfig): AxiosPromise<UserSiteCredentialShortResponse> {
            return localVarFp.getAllUserCredentials(uuid, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанных пользователя, сайта и модуля.
         * @summary Получить зашифрованные учётные данные
         * @param {string} userUuid 
         * @param {number} siteId 
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEncrypted(userUuid: string, siteId: number, moduleId: number, options?: RawAxiosRequestConfig): AxiosPromise<UserCredentialEncrypted> {
            return localVarFp.getEncrypted(userUuid, siteId, moduleId, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанного ID учётной записи.
         * @summary Получить зашифрованные учётные данные по ID
         * @param {number} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEncryptedById(credentialId: number, options?: RawAxiosRequestConfig): AxiosPromise<UserCredentialEncrypted> {
            return localVarFp.getEncryptedById(credentialId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserCredentialsApi - object-oriented interface
 */
export class UserCredentialsApi extends BaseAPI {
    /**
     * Создаёт новую запись учётных данных или обновляет существующую. Возвращает сохранённый объект UserSiteCredential.
     * @summary Создать или обновить учётные данные
     * @param {UserCredentialRequest} userCredentialRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOrUpdate(userCredentialRequest: UserCredentialRequest, options?: RawAxiosRequestConfig) {
        return UserCredentialsApiFp(this.configuration).createOrUpdate(userCredentialRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список всех учётных данных для указанного пользователя (по UUID). Возвращается сокращённая информация (ID, имя, логин, дата создания).
     * @summary Получить все учётные данные пользователя
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllUserCredentials(uuid: string, options?: RawAxiosRequestConfig) {
        return UserCredentialsApiFp(this.configuration).getAllUserCredentials(uuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает логин и зашифрованный пароль для указанных пользователя, сайта и модуля.
     * @summary Получить зашифрованные учётные данные
     * @param {string} userUuid 
     * @param {number} siteId 
     * @param {number} moduleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEncrypted(userUuid: string, siteId: number, moduleId: number, options?: RawAxiosRequestConfig) {
        return UserCredentialsApiFp(this.configuration).getEncrypted(userUuid, siteId, moduleId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает логин и зашифрованный пароль для указанного ID учётной записи.
     * @summary Получить зашифрованные учётные данные по ID
     * @param {number} credentialId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEncryptedById(credentialId: number, options?: RawAxiosRequestConfig) {
        return UserCredentialsApiFp(this.configuration).getEncryptedById(credentialId, options).then((request) => request(this.axios, this.basePath));
    }
}



