/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AccountTemplateBinding {
    'id'?: number;
    'moduleId'?: number;
    'accountId'?: number;
    'templateId'?: number;
    'promtId'?: number;
    'active'?: boolean;
    'userUuid'?: string;
    'notificationType'?: AccountTemplateBindingNotificationTypeEnum;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export const AccountTemplateBindingNotificationTypeEnum = {
    None: 'NONE',
    Email: 'EMAIL',
    Telegram: 'TELEGRAM',
} as const;

export type AccountTemplateBindingNotificationTypeEnum = typeof AccountTemplateBindingNotificationTypeEnum[keyof typeof AccountTemplateBindingNotificationTypeEnum];

export interface BindingCreateRequest {
    /**
     * ID модуля
     */
    'moduleId': number;
    /**
     * ID учётной записи (аккаунта)
     */
    'accountId': number;
    /**
     * ID шаблона
     */
    'templateId': number;
    /**
     * ID промта
     */
    'promtId': number;
    /**
     * Активна ли привязка
     */
    'active'?: boolean;
    /**
     * Тип уведомления
     */
    'notificationType'?: BindingCreateRequestNotificationTypeEnum;
}

export const BindingCreateRequestNotificationTypeEnum = {
    None: 'NONE',
    Email: 'EMAIL',
    Telegram: 'TELEGRAM',
} as const;

export type BindingCreateRequestNotificationTypeEnum = typeof BindingCreateRequestNotificationTypeEnum[keyof typeof BindingCreateRequestNotificationTypeEnum];

export interface BindingResponse {
    /**
     * ID привязки
     */
    'id': number;
    /**
     * ID модуля
     */
    'moduleId': number;
    /**
     * Название модуля
     */
    'moduleName': string;
    /**
     * ID учётной записи
     */
    'accountId': number;
    /**
     * Название учётной записи
     */
    'accountName': string;
    /**
     * ID шаблона
     */
    'templateId': number;
    /**
     * Название шаблона
     */
    'templateName': string;
    /**
     * ID промта
     */
    'promtId': number;
    /**
     * Название промта
     */
    'promtName': string;
    /**
     * Активна ли привязка
     */
    'active': boolean;
    /**
     * Дата создания
     */
    'createdAt': string;
}
export interface BindingUpdateRequest {
    /**
     * ID модуля
     */
    'moduleId': number;
    /**
     * ID учётной записи (аккаунта)
     */
    'accountId': number;
    /**
     * ID шаблона
     */
    'templateId': number;
    /**
     * ID промта
     */
    'promtId': number;
    /**
     * Активна ли привязка
     */
    'active': boolean;
    /**
     * Тип уведомления
     */
    'notificationType': BindingUpdateRequestNotificationTypeEnum;
}

export const BindingUpdateRequestNotificationTypeEnum = {
    None: 'NONE',
    Email: 'EMAIL',
    Telegram: 'TELEGRAM',
} as const;

export type BindingUpdateRequestNotificationTypeEnum = typeof BindingUpdateRequestNotificationTypeEnum[keyof typeof BindingUpdateRequestNotificationTypeEnum];

/**
 * DTO типа уведомления
 */
export interface NotificationTypeDto {
    /**
     * Код типа уведомления
     */
    'code': string;
    /**
     * Описание типа уведомления
     */
    'description': string;
}
/**
 * Информация о поддерживаемом сайте
 */
export interface SiteDTO {
    /**
     * ID сайта
     */
    'id': number;
    /**
     * Название сайта
     */
    'name': string;
}
/**
 * Зашифрованные учётные данные пользователя
 */
export interface UserCredentialEncrypted {
    /**
     * Название учётной записи
     */
    'name': string;
    /**
     * Логин
     */
    'login': string;
    /**
     * Зашифрованный пароль
     */
    'passwordEncrypted': string;
}
export interface UserCredentialRequest {
    'name'?: string;
    'siteId'?: number;
    'login'?: string;
    'password'?: string;
}
export interface UserSiteCredential {
    'id'?: number;
    'name'?: string;
    'siteId'?: number;
    'userUuid'?: string;
    'login'?: string;
    'passwordEncrypted'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
}
/**
 * Сокращённая информация об учётных данных пользователя
 */
export interface UserSiteCredentialShortResponse {
    /**
     * ID учётной записи
     */
    'id': number;
    /**
     * Название учётной записи (например, \'Аккаунт для Kwork\')
     */
    'name': string;
    /**
     * Логин
     */
    'login': string;
    /**
     * Дата создания учётной записи
     */
    'createdAt': string;
}

/**
 * AccountTemplateBindingsApi - axios parameter creator
 */
export const AccountTemplateBindingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Удаляет привязку по её ID.
         * @summary Удалить привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('_delete', 'id', id)
            const localVarPath = `/api/bindings/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Устанавливает статус активности = true для указанной привязки.
         * @summary Активировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('activate', 'id', id)
            const localVarPath = `/api/bindings/{id}/activate`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Создаёт связь между модулем, аккаунтом и шаблоном с указанием активности.
         * @summary Создать новую привязку
         * @param {BindingCreateRequest} bindingCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (bindingCreateRequest: BindingCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bindingCreateRequest' is not null or undefined
            assertParamExists('create', 'bindingCreateRequest', bindingCreateRequest)
            const localVarPath = `/api/bindings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bindingCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Устанавливает статус активности = false для указанной привязки.
         * @summary Деактивировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivate: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deactivate', 'id', id)
            const localVarPath = `/api/bindings/{id}/deactivate`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список привязок для конкретного пользователя (по UUID) и модуля. В случае ошибки возвращает текстовое сообщение.
         * @summary Получить все привязки для пользователя и модуля
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllBindingsForUser: async (moduleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'moduleId' is not null or undefined
            assertParamExists('getAllBindingsForUser', 'moduleId', moduleId)
            const localVarPath = `/api/bindings/module/{moduleId}`
                .replace('{moduleId}', encodeURIComponent(String(moduleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список всех привязок, принадлежащих пользователю (по UUID из заголовка). Возвращаются DTO с расширенной информацией (имена модулей, аккаунтов, шаблонов, промтов).
         * @summary Получить все привязки для текущего пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/bindings/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Устанавливает произвольный статус активности (true/false) для привязки.
         * @summary Установить статус активности
         * @param {number} id 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setActive: async (id: number, active: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('setActive', 'id', id)
            // verify required parameter 'active' is not null or undefined
            assertParamExists('setActive', 'active', active)
            const localVarPath = `/api/bindings/{id}/active`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (active !== undefined) {
                localVarQueryParameter['active'] = active;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Обновляет параметры привязки по её ID.
         * @summary Обновить существующую привязку
         * @param {number} id 
         * @param {BindingUpdateRequest} bindingUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (id: number, bindingUpdateRequest: BindingUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('update', 'id', id)
            // verify required parameter 'bindingUpdateRequest' is not null or undefined
            assertParamExists('update', 'bindingUpdateRequest', bindingUpdateRequest)
            const localVarPath = `/api/bindings/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bindingUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountTemplateBindingsApi - functional programming interface
 */
export const AccountTemplateBindingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountTemplateBindingsApiAxiosParamCreator(configuration)
    return {
        /**
         * Удаляет привязку по её ID.
         * @summary Удалить привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async _delete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator._delete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi._delete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Устанавливает статус активности = true для указанной привязки.
         * @summary Активировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.activate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Создаёт связь между модулем, аккаунтом и шаблоном с указанием активности.
         * @summary Создать новую привязку
         * @param {BindingCreateRequest} bindingCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(bindingCreateRequest: BindingCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTemplateBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(bindingCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.create']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Устанавливает статус активности = false для указанной привязки.
         * @summary Деактивировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deactivate(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTemplateBinding>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deactivate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.deactivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список привязок для конкретного пользователя (по UUID) и модуля. В случае ошибки возвращает текстовое сообщение.
         * @summary Получить все привязки для пользователя и модуля
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllBindingsForUser(moduleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BindingResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllBindingsForUser(moduleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.getAllBindingsForUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список всех привязок, принадлежащих пользователю (по UUID из заголовка). Возвращаются DTO с расширенной информацией (имена модулей, аккаунтов, шаблонов, промтов).
         * @summary Получить все привязки для текущего пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BindingResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.getByUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Устанавливает произвольный статус активности (true/false) для привязки.
         * @summary Установить статус активности
         * @param {number} id 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setActive(id: number, active: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setActive(id, active, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.setActive']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Обновляет параметры привязки по её ID.
         * @summary Обновить существующую привязку
         * @param {number} id 
         * @param {BindingUpdateRequest} bindingUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(id: number, bindingUpdateRequest: BindingUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BindingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(id, bindingUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountTemplateBindingsApi.update']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountTemplateBindingsApi - factory interface
 */
export const AccountTemplateBindingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountTemplateBindingsApiFp(configuration)
    return {
        /**
         * Удаляет привязку по её ID.
         * @summary Удалить привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp._delete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Устанавливает статус активности = true для указанной привязки.
         * @summary Активировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<BindingResponse> {
            return localVarFp.activate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Создаёт связь между модулем, аккаунтом и шаблоном с указанием активности.
         * @summary Создать новую привязку
         * @param {BindingCreateRequest} bindingCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(bindingCreateRequest: BindingCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<AccountTemplateBinding> {
            return localVarFp.create(bindingCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Устанавливает статус активности = false для указанной привязки.
         * @summary Деактивировать привязку
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivate(id: number, options?: RawAxiosRequestConfig): AxiosPromise<AccountTemplateBinding> {
            return localVarFp.deactivate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список привязок для конкретного пользователя (по UUID) и модуля. В случае ошибки возвращает текстовое сообщение.
         * @summary Получить все привязки для пользователя и модуля
         * @param {number} moduleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllBindingsForUser(moduleId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<BindingResponse>> {
            return localVarFp.getAllBindingsForUser(moduleId, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список всех привязок, принадлежащих пользователю (по UUID из заголовка). Возвращаются DTO с расширенной информацией (имена модулей, аккаунтов, шаблонов, промтов).
         * @summary Получить все привязки для текущего пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByUser(options?: RawAxiosRequestConfig): AxiosPromise<Array<BindingResponse>> {
            return localVarFp.getByUser(options).then((request) => request(axios, basePath));
        },
        /**
         * Устанавливает произвольный статус активности (true/false) для привязки.
         * @summary Установить статус активности
         * @param {number} id 
         * @param {boolean} active 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setActive(id: number, active: boolean, options?: RawAxiosRequestConfig): AxiosPromise<BindingResponse> {
            return localVarFp.setActive(id, active, options).then((request) => request(axios, basePath));
        },
        /**
         * Обновляет параметры привязки по её ID.
         * @summary Обновить существующую привязку
         * @param {number} id 
         * @param {BindingUpdateRequest} bindingUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(id: number, bindingUpdateRequest: BindingUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<BindingResponse> {
            return localVarFp.update(id, bindingUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountTemplateBindingsApi - object-oriented interface
 */
export class AccountTemplateBindingsApi extends BaseAPI {
    /**
     * Удаляет привязку по её ID.
     * @summary Удалить привязку
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public _delete(id: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration)._delete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Устанавливает статус активности = true для указанной привязки.
     * @summary Активировать привязку
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public activate(id: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).activate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Создаёт связь между модулем, аккаунтом и шаблоном с указанием активности.
     * @summary Создать новую привязку
     * @param {BindingCreateRequest} bindingCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public create(bindingCreateRequest: BindingCreateRequest, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).create(bindingCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Устанавливает статус активности = false для указанной привязки.
     * @summary Деактивировать привязку
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deactivate(id: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).deactivate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список привязок для конкретного пользователя (по UUID) и модуля. В случае ошибки возвращает текстовое сообщение.
     * @summary Получить все привязки для пользователя и модуля
     * @param {number} moduleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllBindingsForUser(moduleId: number, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).getAllBindingsForUser(moduleId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список всех привязок, принадлежащих пользователю (по UUID из заголовка). Возвращаются DTO с расширенной информацией (имена модулей, аккаунтов, шаблонов, промтов).
     * @summary Получить все привязки для текущего пользователя
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getByUser(options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).getByUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Устанавливает произвольный статус активности (true/false) для привязки.
     * @summary Установить статус активности
     * @param {number} id 
     * @param {boolean} active 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setActive(id: number, active: boolean, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).setActive(id, active, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Обновляет параметры привязки по её ID.
     * @summary Обновить существующую привязку
     * @param {number} id 
     * @param {BindingUpdateRequest} bindingUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public update(id: number, bindingUpdateRequest: BindingUpdateRequest, options?: RawAxiosRequestConfig) {
        return AccountTemplateBindingsApiFp(this.configuration).update(id, bindingUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AutoReplyApi - axios parameter creator
 */
export const AutoReplyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает true, если автоответы включены, иначе false.
         * @summary Получить статус автоответов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/autoreply/status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AutoReplyApi - functional programming interface
 */
export const AutoReplyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AutoReplyApiAxiosParamCreator(configuration)
    return {
        /**
         * Возвращает true, если автоответы включены, иначе false.
         * @summary Получить статус автоответов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AutoReplyApi.getStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AutoReplyApi - factory interface
 */
export const AutoReplyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AutoReplyApiFp(configuration)
    return {
        /**
         * Возвращает true, если автоответы включены, иначе false.
         * @summary Получить статус автоответов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus(options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.getStatus(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AutoReplyApi - object-oriented interface
 */
export class AutoReplyApi extends BaseAPI {
    /**
     * Возвращает true, если автоответы включены, иначе false.
     * @summary Получить статус автоответов
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStatus(options?: RawAxiosRequestConfig) {
        return AutoReplyApiFp(this.configuration).getStatus(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AutoreplySitesSupportingApi - axios parameter creator
 */
export const AutoreplySitesSupportingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает список всех сайтов, для которых доступен парсер автоответов, с ID и названием.
         * @summary Получить список поддерживаемых сайтов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSupportedSites: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/autoreply/supported-sites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AutoreplySitesSupportingApi - functional programming interface
 */
export const AutoreplySitesSupportingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AutoreplySitesSupportingApiAxiosParamCreator(configuration)
    return {
        /**
         * Возвращает список всех сайтов, для которых доступен парсер автоответов, с ID и названием.
         * @summary Получить список поддерживаемых сайтов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSupportedSites(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SiteDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSupportedSites(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AutoreplySitesSupportingApi.getSupportedSites']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AutoreplySitesSupportingApi - factory interface
 */
export const AutoreplySitesSupportingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AutoreplySitesSupportingApiFp(configuration)
    return {
        /**
         * Возвращает список всех сайтов, для которых доступен парсер автоответов, с ID и названием.
         * @summary Получить список поддерживаемых сайтов
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSupportedSites(options?: RawAxiosRequestConfig): AxiosPromise<Array<SiteDTO>> {
            return localVarFp.getSupportedSites(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AutoreplySitesSupportingApi - object-oriented interface
 */
export class AutoreplySitesSupportingApi extends BaseAPI {
    /**
     * Возвращает список всех сайтов, для которых доступен парсер автоответов, с ID и названием.
     * @summary Получить список поддерживаемых сайтов
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSupportedSites(options?: RawAxiosRequestConfig) {
        return AutoreplySitesSupportingApiFp(this.configuration).getSupportedSites(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ModulesApi - axios parameter creator
 */
export const ModulesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает все доступные типы уведомлений с кодами и описаниями. Используется при создании/обновлении биндинга для выбора способа уведомления.
         * @summary Получить список типов уведомлений
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNotificationTypes: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/modules/notification-types`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ModulesApi - functional programming interface
 */
export const ModulesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ModulesApiAxiosParamCreator(configuration)
    return {
        /**
         * Возвращает все доступные типы уведомлений с кодами и описаниями. Используется при создании/обновлении биндинга для выбора способа уведомления.
         * @summary Получить список типов уведомлений
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNotificationTypes(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NotificationTypeDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNotificationTypes(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ModulesApi.getNotificationTypes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ModulesApi - factory interface
 */
export const ModulesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ModulesApiFp(configuration)
    return {
        /**
         * Возвращает все доступные типы уведомлений с кодами и описаниями. Используется при создании/обновлении биндинга для выбора способа уведомления.
         * @summary Получить список типов уведомлений
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNotificationTypes(options?: RawAxiosRequestConfig): AxiosPromise<Array<NotificationTypeDto>> {
            return localVarFp.getNotificationTypes(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ModulesApi - object-oriented interface
 */
export class ModulesApi extends BaseAPI {
    /**
     * Возвращает все доступные типы уведомлений с кодами и описаниями. Используется при создании/обновлении биндинга для выбора способа уведомления.
     * @summary Получить список типов уведомлений
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNotificationTypes(options?: RawAxiosRequestConfig) {
        return ModulesApiFp(this.configuration).getNotificationTypes(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserCredentialsApi - axios parameter creator
 */
export const UserCredentialsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Создаёт новую запись учётных данных или обновляет существующую. Возвращает сохранённый объект UserSiteCredential.
         * @summary Создать или обновить учётные данные
         * @param {UserCredentialRequest} userCredentialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate: async (userCredentialRequest: UserCredentialRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCredentialRequest' is not null or undefined
            assertParamExists('createOrUpdate', 'userCredentialRequest', userCredentialRequest)
            const localVarPath = `/api/credentials/create-or-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCredentialRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет запись учётных данных. Можно удалять только свои записи.
         * @summary Удалить учётные данные по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCredential: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteCredential', 'id', id)
            const localVarPath = `/api/credentials/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает список всех учётных данных для указанного пользователя (по UUID). Возвращается сокращённая информация (ID, имя, логин, дата создания).
         * @summary Получить все учётные данные пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUserCredentials: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/credentials/user/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанного ID учётной записи.
         * @summary Получить зашифрованные учётные данные по ID
         * @param {number} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEncryptedById: async (credentialId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialId' is not null or undefined
            assertParamExists('getEncryptedById', 'credentialId', credentialId)
            const localVarPath = `/api/credentials/get-encrypted-by-id`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (credentialId !== undefined) {
                localVarQueryParameter['credentialId'] = credentialId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserCredentialsApi - functional programming interface
 */
export const UserCredentialsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserCredentialsApiAxiosParamCreator(configuration)
    return {
        /**
         * Создаёт новую запись учётных данных или обновляет существующую. Возвращает сохранённый объект UserSiteCredential.
         * @summary Создать или обновить учётные данные
         * @param {UserCredentialRequest} userCredentialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrUpdate(userCredentialRequest: UserCredentialRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserSiteCredential>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrUpdate(userCredentialRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserCredentialsApi.createOrUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет запись учётных данных. Можно удалять только свои записи.
         * @summary Удалить учётные данные по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCredential(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCredential(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserCredentialsApi.deleteCredential']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает список всех учётных данных для указанного пользователя (по UUID). Возвращается сокращённая информация (ID, имя, логин, дата создания).
         * @summary Получить все учётные данные пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllUserCredentials(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserSiteCredentialShortResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllUserCredentials(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserCredentialsApi.getAllUserCredentials']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанного ID учётной записи.
         * @summary Получить зашифрованные учётные данные по ID
         * @param {number} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEncryptedById(credentialId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserCredentialEncrypted>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEncryptedById(credentialId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserCredentialsApi.getEncryptedById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserCredentialsApi - factory interface
 */
export const UserCredentialsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserCredentialsApiFp(configuration)
    return {
        /**
         * Создаёт новую запись учётных данных или обновляет существующую. Возвращает сохранённый объект UserSiteCredential.
         * @summary Создать или обновить учётные данные
         * @param {UserCredentialRequest} userCredentialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrUpdate(userCredentialRequest: UserCredentialRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserSiteCredential> {
            return localVarFp.createOrUpdate(userCredentialRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет запись учётных данных. Можно удалять только свои записи.
         * @summary Удалить учётные данные по ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCredential(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteCredential(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает список всех учётных данных для указанного пользователя (по UUID). Возвращается сокращённая информация (ID, имя, логин, дата создания).
         * @summary Получить все учётные данные пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllUserCredentials(options?: RawAxiosRequestConfig): AxiosPromise<Array<UserSiteCredentialShortResponse>> {
            return localVarFp.getAllUserCredentials(options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает логин и зашифрованный пароль для указанного ID учётной записи.
         * @summary Получить зашифрованные учётные данные по ID
         * @param {number} credentialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEncryptedById(credentialId: number, options?: RawAxiosRequestConfig): AxiosPromise<UserCredentialEncrypted> {
            return localVarFp.getEncryptedById(credentialId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserCredentialsApi - object-oriented interface
 */
export class UserCredentialsApi extends BaseAPI {
    /**
     * Создаёт новую запись учётных данных или обновляет существующую. Возвращает сохранённый объект UserSiteCredential.
     * @summary Создать или обновить учётные данные
     * @param {UserCredentialRequest} userCredentialRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOrUpdate(userCredentialRequest: UserCredentialRequest, options?: RawAxiosRequestConfig) {
        return UserCredentialsApiFp(this.configuration).createOrUpdate(userCredentialRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет запись учётных данных. Можно удалять только свои записи.
     * @summary Удалить учётные данные по ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCredential(id: number, options?: RawAxiosRequestConfig) {
        return UserCredentialsApiFp(this.configuration).deleteCredential(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает список всех учётных данных для указанного пользователя (по UUID). Возвращается сокращённая информация (ID, имя, логин, дата создания).
     * @summary Получить все учётные данные пользователя
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllUserCredentials(options?: RawAxiosRequestConfig) {
        return UserCredentialsApiFp(this.configuration).getAllUserCredentials(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает логин и зашифрованный пароль для указанного ID учётной записи.
     * @summary Получить зашифрованные учётные данные по ID
     * @param {number} credentialId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getEncryptedById(credentialId: number, options?: RawAxiosRequestConfig) {
        return UserCredentialsApiFp(this.configuration).getEncryptedById(credentialId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserFiltersApi - axios parameter creator
 */
export const UserFiltersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает true, если автоответ включен для указанного модуля, иначе false.
         * @summary Получить статус автоответа для модуля
         * @param {number} moduleId ID модуля
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAutoReplyStatus: async (moduleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'moduleId' is not null or undefined
            assertParamExists('getAutoReplyStatus', 'moduleId', moduleId)
            const localVarPath = `/api/user/module/{module_id}/autoreply`
                .replace('{module_id}', encodeURIComponent(String(moduleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Устанавливает статус автоответа для указанного модуля.
         * @summary Включить/выключить автоответ для модуля
         * @param {number} moduleId ID модуля
         * @param {boolean} enabled Включить автоответ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setAutoReplyStatus: async (moduleId: number, enabled: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'moduleId' is not null or undefined
            assertParamExists('setAutoReplyStatus', 'moduleId', moduleId)
            // verify required parameter 'enabled' is not null or undefined
            assertParamExists('setAutoReplyStatus', 'enabled', enabled)
            const localVarPath = `/api/user/module/{module_id}/autoreply`
                .replace('{module_id}', encodeURIComponent(String(moduleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (enabled !== undefined) {
                localVarQueryParameter['enabled'] = enabled;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserFiltersApi - functional programming interface
 */
export const UserFiltersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserFiltersApiAxiosParamCreator(configuration)
    return {
        /**
         * Возвращает true, если автоответ включен для указанного модуля, иначе false.
         * @summary Получить статус автоответа для модуля
         * @param {number} moduleId ID модуля
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAutoReplyStatus(moduleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAutoReplyStatus(moduleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserFiltersApi.getAutoReplyStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Устанавливает статус автоответа для указанного модуля.
         * @summary Включить/выключить автоответ для модуля
         * @param {number} moduleId ID модуля
         * @param {boolean} enabled Включить автоответ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setAutoReplyStatus(moduleId: number, enabled: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setAutoReplyStatus(moduleId, enabled, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserFiltersApi.setAutoReplyStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserFiltersApi - factory interface
 */
export const UserFiltersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserFiltersApiFp(configuration)
    return {
        /**
         * Возвращает true, если автоответ включен для указанного модуля, иначе false.
         * @summary Получить статус автоответа для модуля
         * @param {number} moduleId ID модуля
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAutoReplyStatus(moduleId: number, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.getAutoReplyStatus(moduleId, options).then((request) => request(axios, basePath));
        },
        /**
         * Устанавливает статус автоответа для указанного модуля.
         * @summary Включить/выключить автоответ для модуля
         * @param {number} moduleId ID модуля
         * @param {boolean} enabled Включить автоответ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setAutoReplyStatus(moduleId: number, enabled: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setAutoReplyStatus(moduleId, enabled, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserFiltersApi - object-oriented interface
 */
export class UserFiltersApi extends BaseAPI {
    /**
     * Возвращает true, если автоответ включен для указанного модуля, иначе false.
     * @summary Получить статус автоответа для модуля
     * @param {number} moduleId ID модуля
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAutoReplyStatus(moduleId: number, options?: RawAxiosRequestConfig) {
        return UserFiltersApiFp(this.configuration).getAutoReplyStatus(moduleId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Устанавливает статус автоответа для указанного модуля.
     * @summary Включить/выключить автоответ для модуля
     * @param {number} moduleId ID модуля
     * @param {boolean} enabled Включить автоответ
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setAutoReplyStatus(moduleId: number, enabled: boolean, options?: RawAxiosRequestConfig) {
        return UserFiltersApiFp(this.configuration).setAutoReplyStatus(moduleId, enabled, options).then((request) => request(this.axios, this.basePath));
    }
}



